/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * ANY CHANGES MADE TO THIS FILE WILL BE LOST
 *
 * File translated:      ../alpha-emulator/idispat.as
 ************************************************************************/

  /* This file implements the main instruction dispatch loop. */
/* start DummyDoNothingSubroutine */


dummydonothingsubroutine:
  if (_trace) printf("dummydonothingsubroutine:\n");
  goto continuecurrentinstruction;   

/* end DummyDoNothingSubroutine */
/* start MemoryReadData */


memoryreaddata:
  if (_trace) printf("memoryreaddata:\n");
  /* Memory Read Internal */

vma_memory_read27698:
  t7 = arg2 + ivory;
  arg6 = (t7 * 4);   
  arg5 = LDQ_U(t7);   
  t5 = arg2 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->dataread_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  arg6 = *(s32 *)arg6;   
  arg5 = (u8)(arg5 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma_memory_read27700;

vma_memory_read27699:
  t7 = zero + 240;   
  t8 = t8 >> (arg5 & 63);   
  t7 = t7 >> (arg5 & 63);   
  arg6 = (u32)arg6;   
  if (t8 & 1)   
    goto vma_memory_read27702;

vma_memory_read27708:
  goto *r0; /* ret */

memoryreaddatadecode:
  if (_trace) printf("memoryreaddatadecode:\n");
  if (t6 == 0) 
    goto vma_memory_read27701;

vma_memory_read27700:
  if (_trace) printf("vma_memory_read27700:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  arg6 = *(s32 *)t5;   
  arg5 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma_memory_read27699;   

vma_memory_read27702:
  if (_trace) printf("vma_memory_read27702:\n");
  if ((t7 & 1) == 0)   
    goto vma_memory_read27701;
  arg2 = (u32)arg6;   		// Do the indirect thing 
  goto vma_memory_read27698;   

vma_memory_read27701:
  if (_trace) printf("vma_memory_read27701:\n");
  t8 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = arg5 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg2;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma_memory_read27705:
  if (_trace) printf("vma_memory_read27705:\n");
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0) 
    goto vma_memory_read27704;
  arg5 = arg5 & ~63L;
  arg5 = arg5 | Type_ExternalValueCellPointer;
  goto vma_memory_read27708;   

vma_memory_read27704:

vma_memory_read27703:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

/* end MemoryReadData */
/* start MemoryReadGeneral */


memoryreadgeneral:
  if (_trace) printf("memoryreadgeneral:\n");
  /* Memory Read Internal */

vma_memory_read27709:
  t7 = arg2 + ivory;
  t8 = (arg3 * 4);   		// Cycle-number -> table offset 
  arg5 = LDQ_U(t7);   
  t8 = (t8 * 4) + ivory;   
  arg6 = (t7 * 4);   
  t5 = arg2 - t11;   		// Stack cache offset 
  t8 = *(u64 *)(t8 + PROCESSORSTATE_DATAREAD_MASK);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  arg6 = *(s32 *)arg6;   
  arg5 = (u8)(arg5 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma_memory_read27711;

vma_memory_read27710:
  t8 = t8 >> (arg5 & 63);   
  arg6 = (u32)arg6;   
  if (t8 & 1)   
    goto vma_memory_read27713;

vma_memory_read27719:
  goto *r0; /* ret */

memoryreadgeneraldecode:
  if (_trace) printf("memoryreadgeneraldecode:\n");
  if (t6 == 0) 
    goto vma_memory_read27712;

vma_memory_read27711:
  if (_trace) printf("vma_memory_read27711:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  arg6 = *(s32 *)t5;   
  arg5 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma_memory_read27710;   

vma_memory_read27713:
  if (_trace) printf("vma_memory_read27713:\n");

vma_memory_read27712:
  if (_trace) printf("vma_memory_read27712:\n");
  t8 = (arg3 * 4);   		// Cycle-number -> table offset 
  t8 = (t8 * 4) + ivory;   
  t8 = *(u64 *)(t8 + PROCESSORSTATE_DATAREAD);   
  /* TagType. */
  t7 = arg5 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg2;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma_memory_read27717:
  if (_trace) printf("vma_memory_read27717:\n");
  t6 = t8 & MemoryActionIndirect;
  if (t6 == 0) 
    goto vma_memory_read27716;
  arg2 = (u32)arg6;   		// Do the indirect thing 
  goto vma_memory_read27709;   

vma_memory_read27716:
  if (_trace) printf("vma_memory_read27716:\n");
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0) 
    goto vma_memory_read27715;
  arg5 = arg5 & ~63L;
  arg5 = arg5 | Type_ExternalValueCellPointer;
  goto vma_memory_read27719;   

vma_memory_read27715:

vma_memory_read27714:
  /* Perform memory action */
  arg1 = t8;
  arg2 = arg3;
  goto performmemoryaction;

/* end MemoryReadGeneral */
/* start MemoryReadHeader */


memoryreadheader:
  if (_trace) printf("memoryreadheader:\n");
  /* Memory Read Internal */

vma_memory_read27720:
  t7 = arg2 + ivory;
  arg6 = (t7 * 4);   
  arg5 = LDQ_U(t7);   
  t5 = arg2 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->header_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  arg6 = *(s32 *)arg6;   
  arg5 = (u8)(arg5 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma_memory_read27722;

vma_memory_read27721:
  t7 = zero + 64;   
  t8 = t8 >> (arg5 & 63);   
  t7 = t7 >> (arg5 & 63);   
  arg6 = (u32)arg6;   
  if (t8 & 1)   
    goto vma_memory_read27724;

vma_memory_read27728:
  goto *r0; /* ret */

memoryreadheaderdecode:
  if (_trace) printf("memoryreadheaderdecode:\n");
  if (t6 == 0) 
    goto vma_memory_read27723;

vma_memory_read27722:
  if (_trace) printf("vma_memory_read27722:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  arg6 = *(s32 *)t5;   
  arg5 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma_memory_read27721;   

vma_memory_read27724:
  if (_trace) printf("vma_memory_read27724:\n");
  if ((t7 & 1) == 0)   
    goto vma_memory_read27723;
  arg2 = (u32)arg6;   		// Do the indirect thing 
  goto vma_memory_read27720;   

vma_memory_read27723:
  if (_trace) printf("vma_memory_read27723:\n");
  t8 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = arg5 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg2;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma_memory_read27725:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end MemoryReadHeader */
/* start MemoryReadCdr */


memoryreadcdr:
  if (_trace) printf("memoryreadcdr:\n");
  /* Memory Read Internal */

vma_memory_read27729:
  t7 = arg2 + ivory;
  arg6 = (t7 * 4);   
  arg5 = LDQ_U(t7);   
  t5 = arg2 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->cdr_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  arg6 = *(s32 *)arg6;   
  arg5 = (u8)(arg5 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma_memory_read27731;

vma_memory_read27730:
  t7 = zero + 192;   
  t8 = t8 >> (arg5 & 63);   
  t7 = t7 >> (arg5 & 63);   
  arg6 = (u32)arg6;   
  if (t8 & 1)   
    goto vma_memory_read27733;

vma_memory_read27737:
  goto *r0; /* ret */

memoryreadcdrdecode:
  if (_trace) printf("memoryreadcdrdecode:\n");
  if (t6 == 0) 
    goto vma_memory_read27732;

vma_memory_read27731:
  if (_trace) printf("vma_memory_read27731:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  arg6 = *(s32 *)t5;   
  arg5 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma_memory_read27730;   

vma_memory_read27733:
  if (_trace) printf("vma_memory_read27733:\n");
  if ((t7 & 1) == 0)   
    goto vma_memory_read27732;
  arg2 = (u32)arg6;   		// Do the indirect thing 
  goto vma_memory_read27729;   

vma_memory_read27732:
  if (_trace) printf("vma_memory_read27732:\n");
  t8 = *(u64 *)&(processor->cdr);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = arg5 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg2;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma_memory_read27734:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 9;
  goto performmemoryaction;

/* end MemoryReadCdr */
/* start DoICacheFill */


doicachefill:
  if (_trace) printf("doicachefill:\n");

ICACHEMISS:
  if (_trace) printf("ICACHEMISS:\n");
  /* Here when instruction cache miss detected.  Fill the cache from */
  /* PC and then resume interpreter loop */
  /* First round the PC down to an even halfword address */
  arg2 = *(u64 *)&(processor->icachebase);   		// get the base of the icache 
  epc = iPC & ~1L;		// the even PC 
  ecp = epc >> (CacheLine_RShift & 63);   
  arg1 = zero + -1;   
  arg1 = arg1 + ((4) << 16);   
  ecp = ecp << (CacheLine_LShift & 63);   
  instn = iPC >> 1;   		// instn is instruction address here 
  ecp = epc + ecp;
  ecp = ecp & arg1;
  arg3 = ecp << 5;   		// temp=cpos*32 
  ecp = ecp << 4;   		// cpos=cpos*16 
  arg4 = arg2 + arg3;		// temp2=base+cpos*32 
  ecp = arg4 + ecp;		// cpos=base+cpos*48 
  opc = epc | 1;		// the odd PC 
  iCP = ecp;		// Assume iPC is the even PC 
  arg1 = (iPC == opc) ? 1 : 0;   		// See if iPC is the odd PC 
  ocp = ecp + CACHELINE_SIZE;
  if (arg1)   		// Stash the odd cache pointer if iPC is the odd PC 
    iCP = ocp;
  hwdispatch = *(u64 *)&(processor->halfworddispatch);   
  hwopmask = zero + 1023;   
  fwdispatch = *(u64 *)&(processor->fullworddispatch);   
  count = zero + 20;   
  t11 = instn + ivory;
  iword = (t11 * 4);   
  arg4 = LDQ_U(t11);   
  iword = *(s32 *)iword;   
  arg4 = (u8)(arg4 >> ((t11&7)*8));   
  goto fillicacheprefetched;   

pcbackone:
  if (_trace) printf("pcbackone:\n");
  /* Wire in continuation for even half */
  *(u64 *)&((CACHELINEP)ocp)->nextpcdata = epc;   
  t10 = ecp - CACHELINE_SIZE;   		// Backup in cache too 
  *(u64 *)&((CACHELINEP)ocp)->nextcp = ecp;   
  arg1 = epc - 1;   		// Backup PC one halfword 
  *(u64 *)&((CACHELINEP)ecp)->nextcp = t10;   
  /* TagType. */
  arg4 = arg4 & 63;		// arg4=tag-cdr code 
  *(u64 *)&((CACHELINEP)ecp)->nextpcdata = arg1;   
  /* Wire in continuation for odd half */
  goto maybeunpack;   

pcadvone:
  if (_trace) printf("pcadvone:\n");
  *(u64 *)&((CACHELINEP)ecp)->nextpcdata = opc;   		// Simple advance of PC one halfword. 
  arg1 = opc + 1;
  *(u64 *)&((CACHELINEP)ecp)->nextcp = ocp;   
  t10 = ocp + CACHELINE_SIZE;
  *(u64 *)&((CACHELINEP)ocp)->nextpcdata = arg1;   
  /* TagType. */
  arg4 = arg4 & 63;		// arg4=tag-cdr code 
  *(u64 *)&((CACHELINEP)ocp)->nextcp = t10;   
  goto maybeunpack;   
  /* This is the cache fill loop. */

fillicache:
  if (_trace) printf("fillicache:\n");
  t11 = instn + ivory;
  iword = (t11 * 4);   
  arg4 = LDQ_U(t11);   
  iword = *(s32 *)iword;   
  arg4 = (u8)(arg4 >> ((t11&7)*8));   

fillicacheprefetched:
  if (_trace) printf("fillicacheprefetched:\n");
  *(u64 *)&((CACHELINEP)ecp)->pcdata = epc;   		// Set address of even cache posn. 
  arg1 = arg4 & 192;		// CDR code << 6 
  /* TagType. */
  arg4 = arg4 & 63;		// Strip cdr 
  *(u64 *)&((CACHELINEP)ocp)->pcdata = opc;   		// Set address of odd cache posn. 
  iword = (u32)iword;   		// Strip nasty bits out. 

force_alignment27738:
  if (_trace) printf("force_alignment27738:\n");
  arg2 = arg4 << 32;   		// ready to remerge 
  if (arg1 == 0) 		// Zerotag means advance one HW 
    goto pcadvone;
  arg1 = arg1 - 128;   		// 2<<6 
  if (arg1 == 0) 		// Tag=2 means backup one HW 
    goto pcbackone;
  if ((s64)arg1 < 0)   		// Tag=1 means end of compiled function 
    goto pcendcf;

pcadvtwo:
  if (_trace) printf("pcadvtwo:\n");
  /* Tag=3 means advance over one full word */
  /* Wire in continuation for even half */
  arg1 = epc + 2;		// Next word 
  r31 = r31 | r31;
  t10 = ecp + TWOCACHELINESIZE;		// corresponding CP entry 
  *(u64 *)&((CACHELINEP)ecp)->nextpcdata = arg1;   		// Next PC even of next word 
  arg1 = epc + 4;		// Skip one fullword 
  *(u64 *)&((CACHELINEP)ecp)->nextcp = t10;   		// Next CP 
  /* Wire in continuation for odd half */
  t10 = ecp + FOURCACHELINESIZE;		// corresponding CP entry 
  *(u64 *)&((CACHELINEP)ocp)->nextpcdata = arg1;   
  /* TagType. */
  arg4 = arg4 & 63;		// arg4=tag-cdr code 
  *(u64 *)&((CACHELINEP)ocp)->nextcp = t10;   
  goto maybeunpack;   

decodepackedword:
  if (_trace) printf("decodepackedword:\n");
  /* Here to decode a packed word */
  arg4 = iword >> 18;   		// arg4 contains the odd packedword 
  t10 = iword >> 8;   		// even opcode+2bits 
  *(u64 *)&((CACHELINEP)ocp)->instruction = arg4;   		// Save the odd instruction 
  t11 = iword << 54;   		// First phase of even operand sign extension. 
  t12 = iword & hwopmask;		// even operand+2bits 
#ifndef CACHEMETERING
  *(u64 *)&((CACHELINEP)ocp)->annotation = zero;   
#endif
  t10 = t10 & hwopmask;		// even opcode 
  t11 = (s64)t11 >> 38;   		// Second phase of even operand sign extension. 
  arg2 = t10 - 92;   
  t10 = (t10 * 8) + hwdispatch;  
  t12 = t11 | t12;		// Merge signed/unsigned even operand 
  arg2 = arg2 & ~3L;
  *(u32 *)&((CACHELINEP)ecp)->operand = t12;
  if (arg2 == 0)   		// clear count if finish-call seen 
    count = arg2;
  arg2 = arg4 >> 8;   		// odd opcode+2bits 
  t11 = arg4 << 54;   		// First phase of odd operand sign extension. 
  arg1 = arg4 & hwopmask;		// odd operand+2bits 
  t10 = *(u64 *)t10;   
  arg2 = arg2 & hwopmask;		// odd opcode 
  t11 = (s64)t11 >> 38;   		// Second phase of odd operand sign extension. 
  *(u64 *)&((CACHELINEP)ecp)->code = t10;   
  t12 = arg2 - 92;   
  arg2 = (arg2 * 8) + hwdispatch;  
  arg1 = t11 | arg1;		// Merge signed/unsigned odd operand 
  *(u32 *)&((CACHELINEP)ocp)->operand = arg1;
  t12 = t12 & ~3L;
  arg2 = *(u64 *)arg2;   
  if (t12 == 0)   		// clear count if finish-call seen 
    count = t12;
  *(u64 *)&((CACHELINEP)ocp)->code = arg2;   
  goto enddecode;   

maybeunpack:
  if (_trace) printf("maybeunpack:\n");
  iword = arg2 | iword;		// reassemble tag and word. 
  *(u64 *)&((CACHELINEP)ecp)->instruction = iword;   		// save the even instruction 
  t10 = arg4 - 48;   		// t10>=0 if packed 
  if ((s64)t10 >= 0)   		// B. if a packed instruction 
    goto decodepackedword;
  t11 = (arg4 * 8) + fwdispatch;  		// t11 is the fwdispatch index 
  t12 = *(u64 *)&(processor->i_stage_error_hook);   
  arg1 = arg4 - 33;   
  t11 = *(u64 *)t11;   		// Extract the opcode handler 
  *(u64 *)&((CACHELINEP)ocp)->code = t12;   		// Store I-STATE-ERROR at odd pc 
  if (arg1 == 0)   		// clear count if native instn seen 
    count = arg1;
  *(u64 *)&((CACHELINEP)ecp)->code = t11;   

enddecode:
  if (_trace) printf("enddecode:\n");
  /* Here we decide if to stop filling the cache and return to the */
  /* instruction interpretation stream, or whether to fill further */
  instn = instn + 1;
  if ((s64)count <= 0)  		// If count is zero, resume 
    goto cachevalid;
  epc = instn << 1;   
  count = count - 1;   		// decrement count 
  opc = epc | 1;
  t10 = *(u64 *)&(processor->endicache);   		// pointer to the end of icache 
  ocp = ocp + TWOCACHELINESIZE;
  ecp = ecp + TWOCACHELINESIZE;
  t10 = ocp - t10;   
  if ((s64)t10 <= 0)  		// Still room for more 
    goto fillicache;
  goto cachevalid;   

pcendcf:
  if (_trace) printf("pcendcf:\n");
  t11 = *(u64 *)&(processor->i_stage_error_hook);   
  count = r31 | r31;		// We reached the end of the fcn. 
  *(u64 *)&((CACHELINEP)ecp)->code = t11;   		// Store I-STATE-ERROR dispatch at even and odd pc 
  *(u64 *)&((CACHELINEP)ocp)->code = t11;   
  goto enddecode;   

/* end DoICacheFill */
  /* These are the instruction reentry points.  Instructions end by returning */
  /* control to one of these tags.  Most normal instructions reenter by jumping */
  /* to NEXTINSTRUCTION, which advances the PC and continues normally.   */
  /* Instructions that change the PC usually go directly to INTERPRETINSTRUCTION. */
  /* Instructions that fail/trap/exception etc, go to one of the other places. */
/* start iInterpret */


iinterpret:
  if (_trace) printf("iinterpret:\n");
  *(u64 *)&processor->asrr9 = r9;   
  *(u64 *)&processor->asrr10 = r10;   
  *(u64 *)&processor->asrr11 = r11;   
  *(u64 *)&processor->asrr12 = r12;   
  *(u64 *)&processor->asrr13 = r13;   
  *(u64 *)&processor->asrr15 = r15;   
  *(u64 *)&processor->asrr26 = r26;   
  *(u64 *)&processor->asrr27 = r27;   
  *(u64 *)&processor->asrr29 = r29;   
  *(u64 *)&processor->asrr30 = r30;   
  *(u64 *)&processor->asrr14 = r14;   
  ivory = arg1;		// Setup our processor object handle 
  /* Upon entry, load cached state. */
  iCP = *(u64 *)&(processor->cp);   
  iPC = *(u64 *)&(processor->epc);   
  iSP = *(u64 *)&(processor->sp);   
  iFP = *(u64 *)&(processor->fp);   
  iLP = *(u64 *)&(processor->lp);   
  if (iCP != 0)   		// First time in iCP will be zero. 
    goto INTERPRETINSTRUCTION;
  goto ICACHEMISS;   		// If this is the first time in cache is empty! 

interpretinstructionpredicted:
  if (_trace) printf("interpretinstructionpredicted:\n");
  t2 = *(u64 *)&(((CACHELINEP)arg2)->pcdata);   		// Get the PC to check cache hit. 
  arg1 = iFP;   		// Assume FP mode 
  r0 = *(u64 *)&(processor->stop_interpreter);   		// Have we been asked to stop? 
  arg4 = iSP + -8;   		// SP-pop mode constant 
  arg3 = *(u64 *)&(((CACHELINEP)arg2)->instruction);   		// Grab the instruction/operand while stalled 
  t1 = iPC - t2;   
  if (t1 != 0)   
    goto interpretinstructionforbranch;
  iCP = arg2;
  if (r0 != 0)   		// Stop the world! someone wants out. 
    goto traporsuspendmachine;
  goto continuecurrentinstruction;   

interpretinstructionforjump:
  if (_trace) printf("interpretinstructionforjump:\n");

interpretinstructionforbranch:
  if (_trace) printf("interpretinstructionforbranch:\n");
  t5 = *(u64 *)&(processor->icachebase);   		// get the base of the icache 
  t4 = zero + -1;   
  t4 = t4 + ((4) << 16);   
  arg2 = iPC >> 10;   
  t3 = zero + -64;   
  arg2 = arg2 & t3;
  arg2 = iPC + arg2;
  arg2 = arg2 & t4;
  t4 = arg2 << 5;   		// temp=cpos*32 
  arg2 = arg2 << 4;   		// cpos=cpos*16 
  t5 = t5 + t4;		// temp2=base+cpos*32 

force_alignment27739:
  if (_trace) printf("force_alignment27739:\n");
  arg2 = t5 + arg2;		// cpos=base+cpos*48 
#ifndef CACHEMETERING
  *(u64 *)&((CACHELINEP)iCP)->annotation = arg2;   
#endif
  iCP = arg2;

INTERPRETINSTRUCTION:
  if (_trace) printf("INTERPRETINSTRUCTION:\n");
  r30 = *(u64 *)&(processor->asrr30);   
  r0 = *(u64 *)&(processor->stop_interpreter);   		// Have we been asked to stop? 
  arg1 = iFP;   		// Assume FP mode 
  arg3 = *(u64 *)&(((CACHELINEP)iCP)->instruction);   		// Grab the instruction/operand while stalled 
  arg4 = iSP + -8;   		// SP-pop mode constant 
  t2 = *(u64 *)&(((CACHELINEP)iCP)->pcdata);   		// Get the PC to check cache hit. 
  if (r0 != 0)   		// Stop the world! someone wants out. 
    goto traporsuspendmachine;
  goto continuecurrentinstruction;   

/* end iInterpret */



/* End of file automatically generated from ../alpha-emulator/idispat.as */
