/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * ANY CHANGES MADE TO THIS FILE WILL BE LOST
 *
 * File translated:      ../alpha-emulator/ifuninst.as
 ************************************************************************/

  /* Instance variable accessors.. */
/* start DoPopInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoPopInstanceVariable */

dopopinstancevariable:
  if (_trace) printf("dopopinstancevariable:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoPopInstanceVariableIM:
  if (_trace) printf("DoPopInstanceVariableIM:\n");

DoPopInstanceVariableSP:
  if (_trace) printf("DoPopInstanceVariableSP:\n");

DoPopInstanceVariableLP:
  if (_trace) printf("DoPopInstanceVariableLP:\n");

DoPopInstanceVariableFP:
  if (_trace) printf("DoPopInstanceVariableFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Mapped */
  arg1 = *(s32 *)(iFP + 16);   		// Map 
  t1 = *(s32 *)(iFP + 20);   
  arg1 = (u32)arg1;   
  t4 = t1 - Type_Array;   
  t4 = t4 & 63;		// Strip CDR code 
  if (t4 != 0)   
    goto ivbadmap;
  /* Memory Read Internal */

vma-memory-read15164:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15166;

vma-memory-read15165:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  if (t10 & 1)   
    goto vma-memory-read15168;

vma-memory-read15173:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;   
  if ((s64)t5 <= 0)  		// J. if mapping-table-index-out-of-bounds 
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

vma-memory-read15174:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->dataread_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15176;

vma-memory-read15175:
  t9 = zero + 240;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15178;

vma-memory-read15185:
  t3 = t2;
  t6 = t1 - Type_Fixnum;   
  t6 = t6 & 63;		// Strip CDR code 
  if (t6 != 0)   
    goto popiviex;
  arg1 = *(s32 *)(iFP + 24);   		// Self 
  t6 = *(s32 *)(iFP + 28);   
  arg1 = (u32)arg1;   
  t5 = t6 - Type_Instance;   
  t5 = t5 & 60;		// Strip CDR code, low bits 
  if (t5 != 0)   
    goto ivbadinst;
  t5 = t6 & 192;		// Unshifted cdr code 
  t5 = t5 - 64;   		// Check for CDR code 1 
  if (t5 != 0)   		// J. if CDR code is not 1 
    goto locate-instance0variable-mapped15163;

locate-instance0variable-mapped15162:
  if (_trace) printf("locate-instance0variable-mapped15162:\n");
  arg1 = arg1 + t3;

locate-instance0variable-mapped15161:
  if (_trace) printf("locate-instance0variable-mapped15161:\n");
  t1 = *(s32 *)iSP;   
  t2 = *(s32 *)(iSP + 4);   
  iSP = iSP - 8;   		// Pop Stack. 
  t1 = (u32)t1;   
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Memory Read Internal */

vma-memory-read15186:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);   
  t4 = LDQ_U(t8);   
  t6 = arg1 - arg5;   		// Stack cache offset 
  t9 = *(u64 *)&(processor->datawrite_mask);   
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;   		// In range? 
  t5 = *(s32 *)t5;   
  t4 = (u8)(t4 >> ((t8&7)*8));   
  if (t7 != 0)   
    goto vma-memory-read15188;

vma-memory-read15187:
  t8 = zero + 240;   
  t9 = t9 >> (t4 & 63);   
  t8 = t8 >> (t4 & 63);   
  if (t9 & 1)   
    goto vma-memory-read15190;

vma-memory-read15196:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);   
  t8 = LDQ_U(t6);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = (t4 & 0xff) << ((t6&7)*8);   
  t8 = t8 & ~(0xffL << (t6&7)*8);   

force-alignment15198:
  if (_trace) printf("force-alignment15198:\n");
  t8 = t8 | t7;
  STQ_U(t6, t8);   
  *(u32 *)t5 = t1;
  if (t9 != 0)   		// J. if in cache 
    goto vma-memory-write15197;
  goto NEXTINSTRUCTION;   
  goto NEXTINSTRUCTION;   

popiviex:
  if (_trace) printf("popiviex:\n");
  t1 = zero + 8;   
  /* SetTag. */
  t1 = t1 << 32;   
  t1 = arg2 | t1;
  arg6 = t2;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 0;		// arg4 = arithmeticp 
  goto exception;

vma-memory-write15197:
  if (_trace) printf("vma-memory-write15197:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t6 = (t7 * 8) + t6;  		// reconstruct SCA 
		/* Store in stack */
  *(u32 *)t6 = t1;
		/* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;   

vma-memory-read15188:
  if (_trace) printf("vma-memory-read15188:\n");
  t7 = *(u64 *)&(processor->stackcachedata);   
  t6 = (t6 * 8) + t7;  		// reconstruct SCA 
  t5 = *(s32 *)t6;   
  t4 = *(s32 *)(t6 + 4);   		// Read from stack cache 
  goto vma-memory-read15187;   

vma-memory-read15190:
  if (_trace) printf("vma-memory-read15190:\n");
  if ((t8 & 1) == 0)   
    goto vma-memory-read15189;
  arg1 = (u32)t5;   		// Do the indirect thing 
  goto vma-memory-read15186;   

vma-memory-read15189:
  if (_trace) printf("vma-memory-read15189:\n");
  t9 = *(u64 *)&(processor->datawrite);   		// Load the memory action table for cycle 
  /* TagType. */
  t8 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t8 = (t8 * 4) + t9;   		// Adjust for a longword load 
  t9 = *(s32 *)t8;   		// Get the memory action 

vma-memory-read15193:

vma-memory-read15192:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

vma-memory-read15176:
  if (_trace) printf("vma-memory-read15176:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15175;   

vma-memory-read15178:
  if (_trace) printf("vma-memory-read15178:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15177;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15174;   

vma-memory-read15177:
  if (_trace) printf("vma-memory-read15177:\n");
  t10 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15182:
  if (_trace) printf("vma-memory-read15182:\n");
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0) 
    goto vma-memory-read15181;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto vma-memory-read15185;   

vma-memory-read15181:

vma-memory-read15180:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15166:
  if (_trace) printf("vma-memory-read15166:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15165;   

vma-memory-read15168:
  if (_trace) printf("vma-memory-read15168:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15167;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15164;   

vma-memory-read15167:
  if (_trace) printf("vma-memory-read15167:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15170:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

locate-instance0variable-mapped15163:
  if (_trace) printf("locate-instance0variable-mapped15163:\n");
  t5 = arg1;
  /* Memory Read Internal */

vma-memory-read15199:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15201;

vma-memory-read15200:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15203;

vma-memory-read15208:
  t5 = t5 - arg1;   
  if (t5 != 0)   
    goto locate-instance0variable-mapped15162;
  /* TagType. */
  t6 = t6 & 63;
  t6 = t6 | 64;		// Set CDR code to 1 
		/* Update self */
  *(u32 *)(iFP + 24) = arg1;
		/* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto locate-instance0variable-mapped15162;   

vma-memory-read15201:
  if (_trace) printf("vma-memory-read15201:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15200;   

vma-memory-read15203:
  if (_trace) printf("vma-memory-read15203:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15202;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15199;   

vma-memory-read15202:
  if (_trace) printf("vma-memory-read15202:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15205:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoPopInstanceVariable */
  /* End of Halfword operand from stack instruction - DoPopInstanceVariable */
/* start DoMovemInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoMovemInstanceVariable */

domoveminstancevariable:
  if (_trace) printf("domoveminstancevariable:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoMovemInstanceVariableIM:
  if (_trace) printf("DoMovemInstanceVariableIM:\n");

DoMovemInstanceVariableSP:
  if (_trace) printf("DoMovemInstanceVariableSP:\n");

DoMovemInstanceVariableLP:
  if (_trace) printf("DoMovemInstanceVariableLP:\n");

DoMovemInstanceVariableFP:
  if (_trace) printf("DoMovemInstanceVariableFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Mapped */
  arg1 = *(s32 *)(iFP + 16);   		// Map 
  t1 = *(s32 *)(iFP + 20);   
  arg1 = (u32)arg1;   
  t4 = t1 - Type_Array;   
  t4 = t4 & 63;		// Strip CDR code 
  if (t4 != 0)   
    goto ivbadmap;
  /* Memory Read Internal */

vma-memory-read15212:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15214;

vma-memory-read15213:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  if (t10 & 1)   
    goto vma-memory-read15216;

vma-memory-read15221:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;   
  if ((s64)t5 <= 0)  		// J. if mapping-table-index-out-of-bounds 
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

vma-memory-read15222:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->dataread_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15224;

vma-memory-read15223:
  t9 = zero + 240;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15226;

vma-memory-read15233:
  t3 = t2;
  t6 = t1 - Type_Fixnum;   
  t6 = t6 & 63;		// Strip CDR code 
  if (t6 != 0)   
    goto movemiviex;
  arg1 = *(s32 *)(iFP + 24);   		// Self 
  t6 = *(s32 *)(iFP + 28);   
  arg1 = (u32)arg1;   
  t5 = t6 - Type_Instance;   
  t5 = t5 & 60;		// Strip CDR code, low bits 
  if (t5 != 0)   
    goto ivbadinst;
  t5 = t6 & 192;		// Unshifted cdr code 
  t5 = t5 - 64;   		// Check for CDR code 1 
  if (t5 != 0)   		// J. if CDR code is not 1 
    goto locate-instance0variable-mapped15211;

locate-instance0variable-mapped15210:
  if (_trace) printf("locate-instance0variable-mapped15210:\n");
  arg1 = arg1 + t3;

locate-instance0variable-mapped15209:
  if (_trace) printf("locate-instance0variable-mapped15209:\n");
  t1 = *(s32 *)iSP;   
  t2 = *(s32 *)(iSP + 4);   
  t1 = (u32)t1;   
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Memory Read Internal */

vma-memory-read15234:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);   
  t4 = LDQ_U(t8);   
  t6 = arg1 - arg5;   		// Stack cache offset 
  t9 = *(u64 *)&(processor->datawrite_mask);   
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;   		// In range? 
  t5 = *(s32 *)t5;   
  t4 = (u8)(t4 >> ((t8&7)*8));   
  if (t7 != 0)   
    goto vma-memory-read15236;

vma-memory-read15235:
  t8 = zero + 240;   
  t9 = t9 >> (t4 & 63);   
  t8 = t8 >> (t4 & 63);   
  if (t9 & 1)   
    goto vma-memory-read15238;

vma-memory-read15244:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);   
  t8 = LDQ_U(t6);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = (t4 & 0xff) << ((t6&7)*8);   
  t8 = t8 & ~(0xffL << (t6&7)*8);   

force-alignment15246:
  if (_trace) printf("force-alignment15246:\n");
  t8 = t8 | t7;
  STQ_U(t6, t8);   
  *(u32 *)t5 = t1;
  if (t9 != 0)   		// J. if in cache 
    goto vma-memory-write15245;
  goto NEXTINSTRUCTION;   
  goto NEXTINSTRUCTION;   

movemiviex:
  if (_trace) printf("movemiviex:\n");
  t1 = zero + 8;   
  /* SetTag. */
  t1 = t1 << 32;   
  t1 = arg2 | t1;
  arg6 = t2;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 0;		// arg4 = arithmeticp 
  goto exception;

vma-memory-write15245:
  if (_trace) printf("vma-memory-write15245:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t6 = (t7 * 8) + t6;  		// reconstruct SCA 
		/* Store in stack */
  *(u32 *)t6 = t1;
		/* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;   

vma-memory-read15236:
  if (_trace) printf("vma-memory-read15236:\n");
  t7 = *(u64 *)&(processor->stackcachedata);   
  t6 = (t6 * 8) + t7;  		// reconstruct SCA 
  t5 = *(s32 *)t6;   
  t4 = *(s32 *)(t6 + 4);   		// Read from stack cache 
  goto vma-memory-read15235;   

vma-memory-read15238:
  if (_trace) printf("vma-memory-read15238:\n");
  if ((t8 & 1) == 0)   
    goto vma-memory-read15237;
  arg1 = (u32)t5;   		// Do the indirect thing 
  goto vma-memory-read15234;   

vma-memory-read15237:
  if (_trace) printf("vma-memory-read15237:\n");
  t9 = *(u64 *)&(processor->datawrite);   		// Load the memory action table for cycle 
  /* TagType. */
  t8 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t8 = (t8 * 4) + t9;   		// Adjust for a longword load 
  t9 = *(s32 *)t8;   		// Get the memory action 

vma-memory-read15241:

vma-memory-read15240:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

vma-memory-read15224:
  if (_trace) printf("vma-memory-read15224:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15223;   

vma-memory-read15226:
  if (_trace) printf("vma-memory-read15226:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15225;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15222;   

vma-memory-read15225:
  if (_trace) printf("vma-memory-read15225:\n");
  t10 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15230:
  if (_trace) printf("vma-memory-read15230:\n");
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0) 
    goto vma-memory-read15229;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto vma-memory-read15233;   

vma-memory-read15229:

vma-memory-read15228:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15214:
  if (_trace) printf("vma-memory-read15214:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15213;   

vma-memory-read15216:
  if (_trace) printf("vma-memory-read15216:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15215;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15212;   

vma-memory-read15215:
  if (_trace) printf("vma-memory-read15215:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15218:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

locate-instance0variable-mapped15211:
  if (_trace) printf("locate-instance0variable-mapped15211:\n");
  t5 = arg1;
  /* Memory Read Internal */

vma-memory-read15247:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15249;

vma-memory-read15248:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15251;

vma-memory-read15256:
  t5 = t5 - arg1;   
  if (t5 != 0)   
    goto locate-instance0variable-mapped15210;
  /* TagType. */
  t6 = t6 & 63;
  t6 = t6 | 64;		// Set CDR code to 1 
		/* Update self */
  *(u32 *)(iFP + 24) = arg1;
		/* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto locate-instance0variable-mapped15210;   

vma-memory-read15249:
  if (_trace) printf("vma-memory-read15249:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15248;   

vma-memory-read15251:
  if (_trace) printf("vma-memory-read15251:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15250;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15247;   

vma-memory-read15250:
  if (_trace) printf("vma-memory-read15250:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15253:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoMovemInstanceVariable */
  /* End of Halfword operand from stack instruction - DoMovemInstanceVariable */
/* start DoPushAddressInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoPushAddressInstanceVariable */

dopushaddressinstancevariable:
  if (_trace) printf("dopushaddressinstancevariable:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoPushAddressInstanceVariableIM:
  if (_trace) printf("DoPushAddressInstanceVariableIM:\n");

DoPushAddressInstanceVariableSP:
  if (_trace) printf("DoPushAddressInstanceVariableSP:\n");

DoPushAddressInstanceVariableLP:
  if (_trace) printf("DoPushAddressInstanceVariableLP:\n");

DoPushAddressInstanceVariableFP:
  if (_trace) printf("DoPushAddressInstanceVariableFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Mapped */
  arg1 = *(s32 *)(iFP + 16);   		// Map 
  t1 = *(s32 *)(iFP + 20);   
  arg1 = (u32)arg1;   
  t4 = t1 - Type_Array;   
  t4 = t4 & 63;		// Strip CDR code 
  if (t4 != 0)   
    goto ivbadmap;
  /* Memory Read Internal */

vma-memory-read15260:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15262;

vma-memory-read15261:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  if (t10 & 1)   
    goto vma-memory-read15264;

vma-memory-read15269:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;   
  if ((s64)t5 <= 0)  		// J. if mapping-table-index-out-of-bounds 
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

vma-memory-read15270:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->dataread_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15272;

vma-memory-read15271:
  t9 = zero + 240;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15274;

vma-memory-read15281:
  t3 = t2;
  t6 = t1 - Type_Fixnum;   
  t6 = t6 & 63;		// Strip CDR code 
  if (t6 != 0)   
    goto pushadiviex;
  arg1 = *(s32 *)(iFP + 24);   		// Self 
  t6 = *(s32 *)(iFP + 28);   
  arg1 = (u32)arg1;   
  t5 = t6 - Type_Instance;   
  t5 = t5 & 60;		// Strip CDR code, low bits 
  if (t5 != 0)   
    goto ivbadinst;
  t5 = t6 & 192;		// Unshifted cdr code 
  t5 = t5 - 64;   		// Check for CDR code 1 
  if (t5 != 0)   		// J. if CDR code is not 1 
    goto locate-instance0variable-mapped15259;

locate-instance0variable-mapped15258:
  if (_trace) printf("locate-instance0variable-mapped15258:\n");
  arg1 = arg1 + t3;

locate-instance0variable-mapped15257:
  if (_trace) printf("locate-instance0variable-mapped15257:\n");
  t7 = Type_Locative;
  *(u32 *)(iSP + 8) = arg1;
		/* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;   

pushadiviex:
  if (_trace) printf("pushadiviex:\n");
  t1 = zero + 8;   
  /* SetTag. */
  t1 = t1 << 32;   
  t1 = arg2 | t1;
  arg6 = t2;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 1;		// arg1 = instruction arity 
  arg4 = 0;		// arg4 = arithmeticp 
  goto exception;

vma-memory-read15272:
  if (_trace) printf("vma-memory-read15272:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15271;   

vma-memory-read15274:
  if (_trace) printf("vma-memory-read15274:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15273;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15270;   

vma-memory-read15273:
  if (_trace) printf("vma-memory-read15273:\n");
  t10 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15278:
  if (_trace) printf("vma-memory-read15278:\n");
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0) 
    goto vma-memory-read15277;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto vma-memory-read15281;   

vma-memory-read15277:

vma-memory-read15276:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15262:
  if (_trace) printf("vma-memory-read15262:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15261;   

vma-memory-read15264:
  if (_trace) printf("vma-memory-read15264:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15263;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15260;   

vma-memory-read15263:
  if (_trace) printf("vma-memory-read15263:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15266:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

locate-instance0variable-mapped15259:
  if (_trace) printf("locate-instance0variable-mapped15259:\n");
  t5 = arg1;
  /* Memory Read Internal */

vma-memory-read15282:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);   
  t1 = LDQ_U(t9);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t10 = *(u64 *)&(processor->header_mask);   
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t1 = (u8)(t1 >> ((t9&7)*8));   
  if (t8 != 0)   
    goto vma-memory-read15284;

vma-memory-read15283:
  t9 = zero + 64;   
  t10 = t10 >> (t1 & 63);   
  t9 = t9 >> (t1 & 63);   
  t2 = (u32)t2;   
  if (t10 & 1)   
    goto vma-memory-read15286;

vma-memory-read15291:
  t5 = t5 - arg1;   
  if (t5 != 0)   
    goto locate-instance0variable-mapped15258;
  /* TagType. */
  t6 = t6 & 63;
  t6 = t6 | 64;		// Set CDR code to 1 
		/* Update self */
  *(u32 *)(iFP + 24) = arg1;
		/* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto locate-instance0variable-mapped15258;   

vma-memory-read15284:
  if (_trace) printf("vma-memory-read15284:\n");
  t8 = *(u64 *)&(processor->stackcachedata);   
  t7 = (t7 * 8) + t8;  		// reconstruct SCA 
  t2 = *(s32 *)t7;   
  t1 = *(s32 *)(t7 + 4);   		// Read from stack cache 
  goto vma-memory-read15283;   

vma-memory-read15286:
  if (_trace) printf("vma-memory-read15286:\n");
  if ((t9 & 1) == 0)   
    goto vma-memory-read15285;
  arg1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15282;   

vma-memory-read15285:
  if (_trace) printf("vma-memory-read15285:\n");
  t10 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t9 = t1 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t9 = (t9 * 4) + t10;   		// Adjust for a longword load 
  t10 = *(s32 *)t9;   		// Get the memory action 

vma-memory-read15288:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoPushAddressInstanceVariable */
  /* End of Halfword operand from stack instruction - DoPushAddressInstanceVariable */
/* start DoPushInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPushInstanceVariableOrdered */

dopushinstancevariableordered:
  if (_trace) printf("dopushinstancevariableordered:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoPushInstanceVariableOrderedIM:
  if (_trace) printf("DoPushInstanceVariableOrderedIM:\n");

DoPushInstanceVariableOrderedSP:
  if (_trace) printf("DoPushInstanceVariableOrderedSP:\n");

DoPushInstanceVariableOrderedLP:
  if (_trace) printf("DoPushInstanceVariableOrderedLP:\n");

DoPushInstanceVariableOrderedFP:
  if (_trace) printf("DoPushInstanceVariableOrderedFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Unmapped */
  t2 = *(s32 *)(iFP + 24);   		// self 
  t1 = *(s32 *)(iFP + 28);   
  t2 = (u32)t2;   
  t3 = t1 - Type_Instance;   
  t3 = t3 & 60;		// Strip CDR code, low bits 
  if (t3 != 0)   
    goto ivbadinst;
  arg1 = t2 + arg2;
  /* Memory Read Internal */

vma-memory-read15292:
  t6 = arg1 + ivory;
  t1 = (t6 * 4);   
  t2 = LDQ_U(t6);   
  t4 = arg1 - arg5;   		// Stack cache offset 
  t7 = *(u64 *)&(processor->dataread_mask);   
  t5 = ((u64)t4 < (u64)arg6) ? 1 : 0;   		// In range? 
  t1 = *(s32 *)t1;   
  t2 = (u8)(t2 >> ((t6&7)*8));   
  if (t5 != 0)   
    goto vma-memory-read15294;

vma-memory-read15293:
  t6 = zero + 240;   
  t7 = t7 >> (t2 & 63);   
  t6 = t6 >> (t2 & 63);   
  if (t7 & 1)   
    goto vma-memory-read15296;

vma-memory-read15303:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  t7 = t2 & 63;		// set CDR-NEXT 
  *(u32 *)(iSP + 8) = t1;
		/* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto cachevalid;   

vma-memory-read15294:
  if (_trace) printf("vma-memory-read15294:\n");
  t5 = *(u64 *)&(processor->stackcachedata);   
  t4 = (t4 * 8) + t5;  		// reconstruct SCA 
  t1 = *(s32 *)t4;   
  t2 = *(s32 *)(t4 + 4);   		// Read from stack cache 
  goto vma-memory-read15293;   

vma-memory-read15296:
  if (_trace) printf("vma-memory-read15296:\n");
  if ((t6 & 1) == 0)   
    goto vma-memory-read15295;
  arg1 = (u32)t1;   		// Do the indirect thing 
  goto vma-memory-read15292;   

vma-memory-read15295:
  if (_trace) printf("vma-memory-read15295:\n");
  t7 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t6 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t6 = (t6 * 4) + t7;   		// Adjust for a longword load 
  t7 = *(s32 *)t6;   		// Get the memory action 

vma-memory-read15300:
  if (_trace) printf("vma-memory-read15300:\n");
  t6 = t7 & MemoryActionTransform;
  if (t6 == 0) 
    goto vma-memory-read15299;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma-memory-read15303;   

vma-memory-read15299:

vma-memory-read15298:
  /* Perform memory action */
  arg1 = t7;
  arg2 = 0;
  goto performmemoryaction;

/* end DoPushInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPushInstanceVariableOrdered */
/* start DoPopInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPopInstanceVariableOrdered */

dopopinstancevariableordered:
  if (_trace) printf("dopopinstancevariableordered:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoPopInstanceVariableOrderedIM:
  if (_trace) printf("DoPopInstanceVariableOrderedIM:\n");

DoPopInstanceVariableOrderedSP:
  if (_trace) printf("DoPopInstanceVariableOrderedSP:\n");

DoPopInstanceVariableOrderedLP:
  if (_trace) printf("DoPopInstanceVariableOrderedLP:\n");

DoPopInstanceVariableOrderedFP:
  if (_trace) printf("DoPopInstanceVariableOrderedFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Unmapped */
  t2 = *(s32 *)(iFP + 24);   		// self 
  t1 = *(s32 *)(iFP + 28);   
  t2 = (u32)t2;   
  t3 = t1 - Type_Instance;   
  t3 = t3 & 60;		// Strip CDR code, low bits 
  if (t3 != 0)   
    goto ivbadinst;
  arg1 = t2 + arg2;
  t1 = *(s32 *)iSP;   
  t2 = *(s32 *)(iSP + 4);   
  iSP = iSP - 8;   		// Pop Stack. 
  t1 = (u32)t1;   
  /* Memory Read Internal */

vma-memory-read15304:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);   
  t4 = LDQ_U(t8);   
  t6 = arg1 - arg5;   		// Stack cache offset 
  t9 = *(u64 *)&(processor->datawrite_mask);   
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;   		// In range? 
  t5 = *(s32 *)t5;   
  t4 = (u8)(t4 >> ((t8&7)*8));   
  if (t7 != 0)   
    goto vma-memory-read15306;

vma-memory-read15305:
  t8 = zero + 240;   
  t9 = t9 >> (t4 & 63);   
  t8 = t8 >> (t4 & 63);   
  if (t9 & 1)   
    goto vma-memory-read15308;

vma-memory-read15314:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);   
  t8 = LDQ_U(t6);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = (t4 & 0xff) << ((t6&7)*8);   
  t8 = t8 & ~(0xffL << (t6&7)*8);   

force-alignment15316:
  if (_trace) printf("force-alignment15316:\n");
  t8 = t8 | t7;
  STQ_U(t6, t8);   
  *(u32 *)t5 = t1;
  if (t9 != 0)   		// J. if in cache 
    goto vma-memory-write15315;
  goto NEXTINSTRUCTION;   
  goto NEXTINSTRUCTION;   

vma-memory-write15315:
  if (_trace) printf("vma-memory-write15315:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t6 = (t7 * 8) + t6;  		// reconstruct SCA 
		/* Store in stack */
  *(u32 *)t6 = t1;
		/* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;   

vma-memory-read15306:
  if (_trace) printf("vma-memory-read15306:\n");
  t7 = *(u64 *)&(processor->stackcachedata);   
  t6 = (t6 * 8) + t7;  		// reconstruct SCA 
  t5 = *(s32 *)t6;   
  t4 = *(s32 *)(t6 + 4);   		// Read from stack cache 
  goto vma-memory-read15305;   

vma-memory-read15308:
  if (_trace) printf("vma-memory-read15308:\n");
  if ((t8 & 1) == 0)   
    goto vma-memory-read15307;
  arg1 = (u32)t5;   		// Do the indirect thing 
  goto vma-memory-read15304;   

vma-memory-read15307:
  if (_trace) printf("vma-memory-read15307:\n");
  t9 = *(u64 *)&(processor->datawrite);   		// Load the memory action table for cycle 
  /* TagType. */
  t8 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t8 = (t8 * 4) + t9;   		// Adjust for a longword load 
  t9 = *(s32 *)t8;   		// Get the memory action 

vma-memory-read15311:

vma-memory-read15310:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

/* end DoPopInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPopInstanceVariableOrdered */
/* start DoMovemInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoMovemInstanceVariableOrdered */

domoveminstancevariableordered:
  if (_trace) printf("domoveminstancevariableordered:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoMovemInstanceVariableOrderedIM:
  if (_trace) printf("DoMovemInstanceVariableOrderedIM:\n");

DoMovemInstanceVariableOrderedSP:
  if (_trace) printf("DoMovemInstanceVariableOrderedSP:\n");

DoMovemInstanceVariableOrderedLP:
  if (_trace) printf("DoMovemInstanceVariableOrderedLP:\n");

DoMovemInstanceVariableOrderedFP:
  if (_trace) printf("DoMovemInstanceVariableOrderedFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Instance Variable Unmapped */
  t2 = *(s32 *)(iFP + 24);   		// self 
  t1 = *(s32 *)(iFP + 28);   
  t2 = (u32)t2;   
  t3 = t1 - Type_Instance;   
  t3 = t3 & 60;		// Strip CDR code, low bits 
  if (t3 != 0)   
    goto ivbadinst;
  arg1 = t2 + arg2;
  t1 = *(s32 *)iSP;   
  t2 = *(s32 *)(iSP + 4);   
  t1 = (u32)t1;   
  /* Memory Read Internal */

vma-memory-read15317:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);   
  t4 = LDQ_U(t8);   
  t6 = arg1 - arg5;   		// Stack cache offset 
  t9 = *(u64 *)&(processor->datawrite_mask);   
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;   		// In range? 
  t5 = *(s32 *)t5;   
  t4 = (u8)(t4 >> ((t8&7)*8));   
  if (t7 != 0)   
    goto vma-memory-read15319;

vma-memory-read15318:
  t8 = zero + 240;   
  t9 = t9 >> (t4 & 63);   
  t8 = t8 >> (t4 & 63);   
  if (t9 & 1)   
    goto vma-memory-read15321;

vma-memory-read15327:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);   
  t8 = LDQ_U(t6);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = (t4 & 0xff) << ((t6&7)*8);   
  t8 = t8 & ~(0xffL << (t6&7)*8);   

force-alignment15329:
  if (_trace) printf("force-alignment15329:\n");
  t8 = t8 | t7;
  STQ_U(t6, t8);   
  *(u32 *)t5 = t1;
  if (t9 != 0)   		// J. if in cache 
    goto vma-memory-write15328;
  goto NEXTINSTRUCTION;   
  goto NEXTINSTRUCTION;   

vma-memory-write15328:
  if (_trace) printf("vma-memory-write15328:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t7 = arg1 - arg5;   		// Stack cache offset 
  t6 = (t7 * 8) + t6;  		// reconstruct SCA 
		/* Store in stack */
  *(u32 *)t6 = t1;
		/* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;   

vma-memory-read15319:
  if (_trace) printf("vma-memory-read15319:\n");
  t7 = *(u64 *)&(processor->stackcachedata);   
  t6 = (t6 * 8) + t7;  		// reconstruct SCA 
  t5 = *(s32 *)t6;   
  t4 = *(s32 *)(t6 + 4);   		// Read from stack cache 
  goto vma-memory-read15318;   

vma-memory-read15321:
  if (_trace) printf("vma-memory-read15321:\n");
  if ((t8 & 1) == 0)   
    goto vma-memory-read15320;
  arg1 = (u32)t5;   		// Do the indirect thing 
  goto vma-memory-read15317;   

vma-memory-read15320:
  if (_trace) printf("vma-memory-read15320:\n");
  t9 = *(u64 *)&(processor->datawrite);   		// Load the memory action table for cycle 
  /* TagType. */
  t8 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg1;   		// stash the VMA for the (likely) trap 
  t8 = (t8 * 4) + t9;   		// Adjust for a longword load 
  t9 = *(s32 *)t8;   		// Get the memory action 

vma-memory-read15324:

vma-memory-read15323:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

/* end DoMovemInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoMovemInstanceVariableOrdered */
/* start DoPushAddressInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPushAddressInstanceVariableOrdered */

dopushaddressinstancevariableordered:
  if (_trace) printf("dopushaddressinstancevariableordered:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoPushAddressInstanceVariableOrderedIM:
  if (_trace) printf("DoPushAddressInstanceVariableOrderedIM:\n");

DoPushAddressInstanceVariableOrderedSP:
  if (_trace) printf("DoPushAddressInstanceVariableOrderedSP:\n");

DoPushAddressInstanceVariableOrderedLP:
  if (_trace) printf("DoPushAddressInstanceVariableOrderedLP:\n");

DoPushAddressInstanceVariableOrderedFP:
  if (_trace) printf("DoPushAddressInstanceVariableOrderedFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  /* Locate Instance Variable Unmapped */
  t2 = *(s32 *)(iFP + 24);   		// self 
  t1 = *(s32 *)(iFP + 28);   
  t2 = (u32)t2;   
  t3 = t1 - Type_Instance;   
  t3 = t3 & 60;		// Strip CDR code, low bits 
  if (t3 != 0)   
    goto ivbadinst;
  arg1 = t2 + arg2;
  t7 = Type_Locative;
  *(u32 *)(iSP + 8) = arg1;
		/* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;   

ivbadmap:
  if (_trace) printf("ivbadmap:\n");
  arg5 = 0;
  arg2 = 68;
  goto illegaloperand;

ivbadindex:
  if (_trace) printf("ivbadindex:\n");
  arg5 = 0;
  arg2 = 53;
  goto illegaloperand;

ivbadinst:
  if (_trace) printf("ivbadinst:\n");
  arg5 = 0;
  arg2 = 69;
  goto illegaloperand;

/* end DoPushAddressInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPushAddressInstanceVariableOrdered */
/* start DoInstanceRef */

  /* Halfword operand from stack instruction - DoInstanceRef */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceref:
  if (_trace) printf("doinstanceref:\n");

DoInstanceRefIM:
  if (_trace) printf("DoInstanceRefIM:\n");
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);   
  goto begindoinstanceref;   

DoInstanceRefSP:
  if (_trace) printf("DoInstanceRefSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoInstanceRefLP:
  if (_trace) printf("DoInstanceRefLP:\n");

DoInstanceRefFP:
  if (_trace) printf("DoInstanceRefFP:\n");

headdoinstanceref:
  if (_trace) printf("headdoinstanceref:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoinstanceref:
  if (_trace) printf("begindoinstanceref:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;   
  arg3 = *(s32 *)(iSP + 4);   
  arg4 = (u32)arg4;   
  arg2 = arg1 >> 32;   
  arg1 = (u32)arg1;   
  t11 = *(u64 *)&(processor->stackcachebasevma);   
  t12 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;   
  t1 = t1 & 60;		// Strip CDR code, low bits 
  if (t1 != 0)   
    goto ivrefbadinst;
  t1 = arg2 - Type_Fixnum;   
  t1 = t1 & 63;		// Strip CDR code 
  if (t1 != 0)   
    goto ivrefbadoffset;
  /* Memory Read Internal */

vma-memory-read15330:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);   
  t2 = LDQ_U(t7);   
  t5 = arg4 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->header_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t1 = *(s32 *)t1;   
  t2 = (u8)(t2 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15332;

vma-memory-read15331:
  t7 = zero + 64;   
  t8 = t8 >> (t2 & 63);   
  t7 = t7 >> (t2 & 63);   
  t1 = (u32)t1;   
  if (t8 & 1)   
    goto vma-memory-read15334;

vma-memory-read15339:
  t1 = t1 - 1;   
  /* Memory Read Internal */

vma-memory-read15340:
  t7 = t1 + ivory;
  t2 = (t7 * 4);   
  t4 = LDQ_U(t7);   
  t5 = t1 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->dataread_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t4 = (u8)(t4 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15342;

vma-memory-read15341:
  t7 = zero + 240;   
  t8 = t8 >> (t4 & 63);   
  t7 = t7 >> (t4 & 63);   
  if (t8 & 1)   
    goto vma-memory-read15344;

vma-memory-read15351:
  t5 = t4 - Type_Fixnum;   
  t5 = t5 & 63;		// Strip CDR code 
  if (t5 != 0)   
    goto ivrefbadoffset;
  if ((s64)arg1 < 0)   		// J. if offset <0 
    goto ivrefbadoffset;
  t4 = arg1 - t2;   
  if ((s64)t4 >= 0)   		// J. if offset out of bounds 
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  /* Memory Read Internal */

vma-memory-read15352:
  t4 = *(u64 *)&(processor->stackcachebasevma);   		// Base of stack cache 
  t6 = arg5 + ivory;
  t5 = *(s32 *)&processor->scovlimit;   
  t1 = (t6 * 4);   
  t2 = LDQ_U(t6);   
  t4 = arg5 - t4;   		// Stack cache offset 
  t7 = *(u64 *)&(processor->dataread_mask);   
  t5 = ((u64)t4 < (u64)t5) ? 1 : 0;   		// In range? 
  t1 = *(s32 *)t1;   
  t2 = (u8)(t2 >> ((t6&7)*8));   
  if (t5 != 0)   
    goto vma-memory-read15354;

vma-memory-read15353:
  t6 = zero + 240;   
  t7 = t7 >> (t2 & 63);   
  t6 = t6 >> (t2 & 63);   
  if (t7 & 1)   
    goto vma-memory-read15356;

vma-memory-read15363:
  t2 = t2 & 63;		// set CDR-NEXT 
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  *(u32 *)iSP = t1;
		/* write the stack cache */
  *(u32 *)(iSP + 4) = t2;
  goto cachevalid;   

vma-memory-read15354:
  if (_trace) printf("vma-memory-read15354:\n");
  t5 = *(u64 *)&(processor->stackcachedata);   
  t4 = (t4 * 8) + t5;  		// reconstruct SCA 
  t1 = *(s32 *)t4;   
  t2 = *(s32 *)(t4 + 4);   		// Read from stack cache 
  goto vma-memory-read15353;   

vma-memory-read15356:
  if (_trace) printf("vma-memory-read15356:\n");
  if ((t6 & 1) == 0)   
    goto vma-memory-read15355;
  arg5 = (u32)t1;   		// Do the indirect thing 
  goto vma-memory-read15352;   

vma-memory-read15355:
  if (_trace) printf("vma-memory-read15355:\n");
  t7 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t6 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg5;   		// stash the VMA for the (likely) trap 
  t6 = (t6 * 4) + t7;   		// Adjust for a longword load 
  t7 = *(s32 *)t6;   		// Get the memory action 

vma-memory-read15360:
  if (_trace) printf("vma-memory-read15360:\n");
  t6 = t7 & MemoryActionTransform;
  if (t6 == 0) 
    goto vma-memory-read15359;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma-memory-read15363;   

vma-memory-read15359:

vma-memory-read15358:
  /* Perform memory action */
  arg1 = t7;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15342:
  if (_trace) printf("vma-memory-read15342:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t2 = *(s32 *)t5;   
  t4 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15341;   

vma-memory-read15344:
  if (_trace) printf("vma-memory-read15344:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15343;
  t1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15340;   

vma-memory-read15343:
  if (_trace) printf("vma-memory-read15343:\n");
  t8 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t1;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15348:
  if (_trace) printf("vma-memory-read15348:\n");
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0) 
    goto vma-memory-read15347;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto vma-memory-read15351;   

vma-memory-read15347:

vma-memory-read15346:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15332:
  if (_trace) printf("vma-memory-read15332:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t1 = *(s32 *)t5;   
  t2 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15331;   

vma-memory-read15334:
  if (_trace) printf("vma-memory-read15334:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15333;
  arg4 = (u32)t1;   		// Do the indirect thing 
  goto vma-memory-read15330;   

vma-memory-read15333:
  if (_trace) printf("vma-memory-read15333:\n");
  t8 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg4;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15336:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceRef */
  /* End of Halfword operand from stack instruction - DoInstanceRef */
/* start DoInstanceSet */

  /* Halfword operand from stack instruction - DoInstanceSet */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceset:
  if (_trace) printf("doinstanceset:\n");

DoInstanceSetIM:
  if (_trace) printf("DoInstanceSetIM:\n");
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);   
  goto begindoinstanceset;   

DoInstanceSetSP:
  if (_trace) printf("DoInstanceSetSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoInstanceSetLP:
  if (_trace) printf("DoInstanceSetLP:\n");

DoInstanceSetFP:
  if (_trace) printf("DoInstanceSetFP:\n");

headdoinstanceset:
  if (_trace) printf("headdoinstanceset:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoinstanceset:
  if (_trace) printf("begindoinstanceset:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;   
  arg3 = *(s32 *)(iSP + 4);   
  iSP = iSP - 8;   		// Pop Stack. 
  arg4 = (u32)arg4;   
  arg2 = arg1 >> 32;   
  arg1 = (u32)arg1;   
  t11 = *(u64 *)&(processor->stackcachebasevma);   
  t12 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;   
  t1 = t1 & 60;		// Strip CDR code, low bits 
  if (t1 != 0)   
    goto ivrefbadinst3;
  t1 = arg2 - Type_Fixnum;   
  t1 = t1 & 63;		// Strip CDR code 
  if (t1 != 0)   
    goto ivrefbadoffset;
  /* Memory Read Internal */

vma-memory-read15364:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);   
  t2 = LDQ_U(t7);   
  t5 = arg4 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->header_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t1 = *(s32 *)t1;   
  t2 = (u8)(t2 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15366;

vma-memory-read15365:
  t7 = zero + 64;   
  t8 = t8 >> (t2 & 63);   
  t7 = t7 >> (t2 & 63);   
  t1 = (u32)t1;   
  if (t8 & 1)   
    goto vma-memory-read15368;

vma-memory-read15373:
  t1 = t1 - 1;   
  /* Memory Read Internal */

vma-memory-read15374:
  t7 = t1 + ivory;
  t2 = (t7 * 4);   
  t4 = LDQ_U(t7);   
  t5 = t1 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->dataread_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t4 = (u8)(t4 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15376;

vma-memory-read15375:
  t7 = zero + 240;   
  t8 = t8 >> (t4 & 63);   
  t7 = t7 >> (t4 & 63);   
  if (t8 & 1)   
    goto vma-memory-read15378;

vma-memory-read15385:
  t5 = t4 - Type_Fixnum;   
  t5 = t5 & 63;		// Strip CDR code 
  if (t5 != 0)   
    goto ivrefbadoffset;
  if ((s64)arg1 < 0)   		// J. if offset <0 
    goto ivrefbadoffset;
  t4 = arg1 - t2;   
  if ((s64)t4 >= 0)   		// J. if offset out of bounds 
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  t1 = *(s32 *)iSP;   
  t2 = *(s32 *)(iSP + 4);   
  iSP = iSP - 8;   		// Pop Stack. 
  t1 = (u32)t1;   
  t11 = *(u64 *)&(processor->stackcachebasevma);   
  t12 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Memory Read Internal */

vma-memory-read15386:
  t7 = arg5 + ivory;
  t4 = (t7 * 4);   
  t3 = LDQ_U(t7);   
  t5 = arg5 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->datawrite_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t4 = *(s32 *)t4;   
  t3 = (u8)(t3 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15388;

vma-memory-read15387:
  t7 = zero + 240;   
  t8 = t8 >> (t3 & 63);   
  t7 = t7 >> (t3 & 63);   
  if (t8 & 1)   
    goto vma-memory-read15390;

vma-memory-read15396:
  /* Merge cdr-code */
  t4 = t2 & 63;
  t3 = t3 & 192;
  t3 = t3 | t4;
  t5 = arg5 + ivory;
  t4 = (t5 * 4);   
  t7 = LDQ_U(t5);   
  t6 = arg5 - t11;   		// Stack cache offset 
  t8 = ((u64)t6 < (u64)t12) ? 1 : 0;   		// In range? 
  t6 = (t3 & 0xff) << ((t5&7)*8);   
  t7 = t7 & ~(0xffL << (t5&7)*8);   

force-alignment15398:
  if (_trace) printf("force-alignment15398:\n");
  t7 = t7 | t6;
  STQ_U(t5, t7);   
  *(u32 *)t4 = t1;
  if (t8 != 0)   		// J. if in cache 
    goto vma-memory-write15397;
  goto NEXTINSTRUCTION;   
  goto NEXTINSTRUCTION;   

ivrefbadinst3:
  if (_trace) printf("ivrefbadinst3:\n");
  arg5 = 0;
  arg2 = 4;
  goto illegaloperand;

vma-memory-write15397:
  if (_trace) printf("vma-memory-write15397:\n");
  t5 = *(u64 *)&(processor->stackcachedata);   
  t6 = arg5 - t11;   		// Stack cache offset 
  t5 = (t6 * 8) + t5;  		// reconstruct SCA 
		/* Store in stack */
  *(u32 *)t5 = t1;
		/* write the stack cache */
  *(u32 *)(t5 + 4) = t3;
  goto NEXTINSTRUCTION;   

vma-memory-read15388:
  if (_trace) printf("vma-memory-read15388:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t4 = *(s32 *)t5;   
  t3 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15387;   

vma-memory-read15390:
  if (_trace) printf("vma-memory-read15390:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15389;
  arg5 = (u32)t4;   		// Do the indirect thing 
  goto vma-memory-read15386;   

vma-memory-read15389:
  if (_trace) printf("vma-memory-read15389:\n");
  t8 = *(u64 *)&(processor->datawrite);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t3 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg5;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15393:

vma-memory-read15392:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 1;
  goto performmemoryaction;

vma-memory-read15376:
  if (_trace) printf("vma-memory-read15376:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t2 = *(s32 *)t5;   
  t4 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15375;   

vma-memory-read15378:
  if (_trace) printf("vma-memory-read15378:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15377;
  t1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15374;   

vma-memory-read15377:
  if (_trace) printf("vma-memory-read15377:\n");
  t8 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t1;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15382:
  if (_trace) printf("vma-memory-read15382:\n");
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0) 
    goto vma-memory-read15381;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto vma-memory-read15385;   

vma-memory-read15381:

vma-memory-read15380:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15366:
  if (_trace) printf("vma-memory-read15366:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t1 = *(s32 *)t5;   
  t2 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15365;   

vma-memory-read15368:
  if (_trace) printf("vma-memory-read15368:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15367;
  arg4 = (u32)t1;   		// Do the indirect thing 
  goto vma-memory-read15364;   

vma-memory-read15367:
  if (_trace) printf("vma-memory-read15367:\n");
  t8 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg4;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15370:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceSet */
  /* End of Halfword operand from stack instruction - DoInstanceSet */
/* start DoInstanceLoc */

  /* Halfword operand from stack instruction - DoInstanceLoc */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceloc:
  if (_trace) printf("doinstanceloc:\n");

DoInstanceLocIM:
  if (_trace) printf("DoInstanceLocIM:\n");
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);   
  goto begindoinstanceloc;   

DoInstanceLocSP:
  if (_trace) printf("DoInstanceLocSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoInstanceLocLP:
  if (_trace) printf("DoInstanceLocLP:\n");

DoInstanceLocFP:
  if (_trace) printf("DoInstanceLocFP:\n");

headdoinstanceloc:
  if (_trace) printf("headdoinstanceloc:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoinstanceloc:
  if (_trace) printf("begindoinstanceloc:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;   
  arg3 = *(s32 *)(iSP + 4);   
  arg4 = (u32)arg4;   
  arg2 = arg1 >> 32;   
  arg1 = (u32)arg1;   
  t11 = *(u64 *)&(processor->stackcachebasevma);   
  t12 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;   
  t1 = t1 & 60;		// Strip CDR code, low bits 
  if (t1 != 0)   
    goto ivrefbadinst;
  t1 = arg2 - Type_Fixnum;   
  t1 = t1 & 63;		// Strip CDR code 
  if (t1 != 0)   
    goto ivrefbadoffset;
  /* Memory Read Internal */

vma-memory-read15399:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);   
  t2 = LDQ_U(t7);   
  t5 = arg4 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->header_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t1 = *(s32 *)t1;   
  t2 = (u8)(t2 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15401;

vma-memory-read15400:
  t7 = zero + 64;   
  t8 = t8 >> (t2 & 63);   
  t7 = t7 >> (t2 & 63);   
  t1 = (u32)t1;   
  if (t8 & 1)   
    goto vma-memory-read15403;

vma-memory-read15408:
  t1 = t1 - 1;   
  /* Memory Read Internal */

vma-memory-read15409:
  t7 = t1 + ivory;
  t2 = (t7 * 4);   
  t4 = LDQ_U(t7);   
  t5 = t1 - t11;   		// Stack cache offset 
  t8 = *(u64 *)&(processor->dataread_mask);   
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;   		// In range? 
  t2 = *(s32 *)t2;   
  t4 = (u8)(t4 >> ((t7&7)*8));   
  if (t6 != 0)   
    goto vma-memory-read15411;

vma-memory-read15410:
  t7 = zero + 240;   
  t8 = t8 >> (t4 & 63);   
  t7 = t7 >> (t4 & 63);   
  if (t8 & 1)   
    goto vma-memory-read15413;

vma-memory-read15420:
  t5 = t4 - Type_Fixnum;   
  t5 = t5 & 63;		// Strip CDR code 
  if (t5 != 0)   
    goto ivrefbadoffset;
  if ((s64)arg1 < 0)   		// J. if offset <0 
    goto ivrefbadoffset;
  t4 = arg1 - t2;   
  if ((s64)t4 >= 0)   		// J. if offset out of bounds 
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  t7 = Type_Locative;
  *(u32 *)iSP = arg5;
		/* write the stack cache */
  *(u32 *)(iSP + 4) = t7;
  goto NEXTINSTRUCTION;   

ivrefbadinst:
  if (_trace) printf("ivrefbadinst:\n");
  arg5 = 0;
  arg2 = 3;
  goto illegaloperand;

ivrefbadoffset:
  if (_trace) printf("ivrefbadoffset:\n");
  arg5 = 0;
  arg2 = 49;
  goto illegaloperand;

vma-memory-read15411:
  if (_trace) printf("vma-memory-read15411:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t2 = *(s32 *)t5;   
  t4 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15410;   

vma-memory-read15413:
  if (_trace) printf("vma-memory-read15413:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15412;
  t1 = (u32)t2;   		// Do the indirect thing 
  goto vma-memory-read15409;   

vma-memory-read15412:
  if (_trace) printf("vma-memory-read15412:\n");
  t8 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t4 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t1;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15417:
  if (_trace) printf("vma-memory-read15417:\n");
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0) 
    goto vma-memory-read15416;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto vma-memory-read15420;   

vma-memory-read15416:

vma-memory-read15415:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

vma-memory-read15401:
  if (_trace) printf("vma-memory-read15401:\n");
  t6 = *(u64 *)&(processor->stackcachedata);   
  t5 = (t5 * 8) + t6;  		// reconstruct SCA 
  t1 = *(s32 *)t5;   
  t2 = *(s32 *)(t5 + 4);   		// Read from stack cache 
  goto vma-memory-read15400;   

vma-memory-read15403:
  if (_trace) printf("vma-memory-read15403:\n");
  if ((t7 & 1) == 0)   
    goto vma-memory-read15402;
  arg4 = (u32)t1;   		// Do the indirect thing 
  goto vma-memory-read15399;   

vma-memory-read15402:
  if (_trace) printf("vma-memory-read15402:\n");
  t8 = *(u64 *)&(processor->header);   		// Load the memory action table for cycle 
  /* TagType. */
  t7 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg4;   		// stash the VMA for the (likely) trap 
  t7 = (t7 * 4) + t8;   		// Adjust for a longword load 
  t8 = *(s32 *)t7;   		// Get the memory action 

vma-memory-read15405:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceLoc */
  /* End of Halfword operand from stack instruction - DoInstanceLoc */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifuninst.as */
