/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * ANY CHANGES MADE TO THIS FILE WILL BE LOST
 *
 * File translated:      ../alpha-emulator/ifunblok.as
 ************************************************************************/

  /* Block Instructions. */
/* start DoBlock0Read */

  /* Halfword 10 bit immediate instruction - DoBlock0Read */

doblock0read:
  if (_trace) printf("doblock0read:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadIM:
  if (_trace) printf("DoBlock0ReadIM:\n");

DoBlock0ReadSP:
  if (_trace) printf("DoBlock0ReadSP:\n");

DoBlock0ReadLP:
  if (_trace) printf("DoBlock0ReadLP:\n");

DoBlock0ReadFP:
  if (_trace) printf("DoBlock0ReadFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockread;   

/* end DoBlock0Read */
  /* End of Halfword operand from stack instruction - DoBlock0Read */
/* start DoBlock0Write */

  /* Halfword operand from stack instruction - DoBlock0Write */

doblock0write:
  if (_trace) printf("doblock0write:\n");
  /* arg2 has the preloaded 8 bit operand. */

DoBlock0WriteIM:
  if (_trace) printf("DoBlock0WriteIM:\n");
  /* This sequence only sucks a moderate amount */
  arg2 = arg2 << 56;   		// sign extend the byte argument. 

force_alignment32480:
  if (_trace) printf("force_alignment32480:\n");
  arg2 = (s64)arg2 >> 56;   		// Rest of sign extension 
  *(u32 *)&processor->immediate_arg = arg2;   
  arg1 = *(u64 *)&(processor->immediate_arg);   
  goto begindoblock0write;   

DoBlock0WriteSP:
  if (_trace) printf("DoBlock0WriteSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock0WriteLP:
  if (_trace) printf("DoBlock0WriteLP:\n");

DoBlock0WriteFP:
  if (_trace) printf("DoBlock0WriteFP:\n");

headdoblock0write:
  if (_trace) printf("headdoblock0write:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoblock0write:
  if (_trace) printf("begindoblock0write:\n");
  /* arg1 has the operand, sign extended if immediate. */
  arg3 = *(s32 *)&processor->bar0;   
  arg2 = (u64)&processor->bar0;   
  goto blockwrite;   

/* end DoBlock0Write */
  /* End of Halfword operand from stack instruction - DoBlock0Write */
/* start DoBlock0ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadShift */

doblock0readshift:
  if (_trace) printf("doblock0readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadShiftIM:
  if (_trace) printf("DoBlock0ReadShiftIM:\n");

DoBlock0ReadShiftSP:
  if (_trace) printf("DoBlock0ReadShiftSP:\n");

DoBlock0ReadShiftLP:
  if (_trace) printf("DoBlock0ReadShiftLP:\n");

DoBlock0ReadShiftFP:
  if (_trace) printf("DoBlock0ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockreadshift;   

/* end DoBlock0ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock0ReadShift */
/* start DoBlock3ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadShift */

doblock3readshift:
  if (_trace) printf("doblock3readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock3ReadShiftIM:
  if (_trace) printf("DoBlock3ReadShiftIM:\n");

DoBlock3ReadShiftSP:
  if (_trace) printf("DoBlock3ReadShiftSP:\n");

DoBlock3ReadShiftLP:
  if (_trace) printf("DoBlock3ReadShiftLP:\n");

DoBlock3ReadShiftFP:
  if (_trace) printf("DoBlock3ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;   
  goto blockreadshift;   

/* end DoBlock3ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock3ReadShift */
/* start DoBlock2ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadShift */

doblock2readshift:
  if (_trace) printf("doblock2readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock2ReadShiftIM:
  if (_trace) printf("DoBlock2ReadShiftIM:\n");

DoBlock2ReadShiftSP:
  if (_trace) printf("DoBlock2ReadShiftSP:\n");

DoBlock2ReadShiftLP:
  if (_trace) printf("DoBlock2ReadShiftLP:\n");

DoBlock2ReadShiftFP:
  if (_trace) printf("DoBlock2ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;   
  goto blockreadshift;   

/* end DoBlock2ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock2ReadShift */
/* start DoBlock1ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadShift */

doblock1readshift:
  if (_trace) printf("doblock1readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock1ReadShiftIM:
  if (_trace) printf("DoBlock1ReadShiftIM:\n");

DoBlock1ReadShiftSP:
  if (_trace) printf("DoBlock1ReadShiftSP:\n");

DoBlock1ReadShiftLP:
  if (_trace) printf("DoBlock1ReadShiftLP:\n");

DoBlock1ReadShiftFP:
  if (_trace) printf("DoBlock1ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;   

blockreadshift:
  if (_trace) printf("blockreadshift:\n");
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  t2 = *(s32 *)arg2;   		// Get the vma 
  t1 = arg1 >> 6;   		// cycle type 
  t4 = arg1 & 4;		// =no-incrementp 
  t5 = arg1 & 16;		// =cdr-code-nextp 
  t6 = arg1 & 32;		// =fixnum onlyp 
  t2 = (u32)t2;   
  /* Memory Read Internal */

vma_memory_read32485:
  t11 = t2 + ivory;
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t8 = LDQ_U(t11);   
  t12 = (t12 * 4) + ivory;   
  t7 = (t11 * 4);   
  t9 = t2 - arg5;   		// Stack cache offset 
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);   
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = *(s32 *)t7;   
  t8 = (u8)(t8 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma_memory_read32487;

vma_memory_read32486:
  t12 = t12 >> (t8 & 63);   
  t7 = (u32)t7;   
  if (t12 & 1)   
    goto vma_memory_read32489;

vma_memory_read32496:
  if (t6 == 0) 		// J. if we don't have to test for fixnump. 
    goto i_block_n_read_shift32481;
  t9 = t8 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i_block_n_read_shift32484;

i_block_n_read_shift32481:
  if (_trace) printf("i_block_n_read_shift32481:\n");
  if (t4 != 0)   		// J. if we don't have to increment the address. 
    goto i_block_n_read_shift32482;
  t2 = t2 + 1;		// Increment the address 

i_block_n_read_shift32482:
  if (_trace) printf("i_block_n_read_shift32482:\n");
  *(u32 *)arg2 = t2;   		// Store updated vma in BAR 
  if (t5 == 0) 		// J. if we don't have to clear CDR codes. 
    goto i_block_n_read_shift32483;
  t8 = t8 & 63;

i_block_n_read_shift32483:
  if (_trace) printf("i_block_n_read_shift32483:\n");
  t1 = zero + 21504;   
  t3 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t4 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t2 = t1 >> 10;   
  t2 = t2 & 3;		// Extract the byte background 
  t5 = (t2 == ALUByteBackground_Op1) ? 1 : 0;   

force_alignment32503:
  if (_trace) printf("force_alignment32503:\n");
  if (t5 == 0) 
    goto basic_dispatch32499;
  /* Here if argument ALUByteBackgroundOp1 */
  t2 = t1;

basic_dispatch32498:
  if (_trace) printf("basic_dispatch32498:\n");
  t6 = t1 >> 12;   
  t6 = t6 & 1;		// Extractthe byte rotate latch 
  t7 = t7 << (t3 & 63);   
  t5 = (u32)(t7 >> ((4&7)*8));   
  t7 = (u32)t7;   
  t7 = t7 | t5;		// OP2 rotated 
  if (t6 == 0) 		// Don't update rotate latch if not requested 
    goto alu_function_byte32497;
  *(u64 *)&processor->rotatelatch = t7;   

alu_function_byte32497:
  if (_trace) printf("alu_function_byte32497:\n");
  t6 = zero + -2;   
  t6 = t6 << (t4 & 63);   
  t6 = ~t6;   		// Compute mask 
  /* Get byte function */
  t5 = t1 >> 13;   
  t5 = t5 & 1;
  t4 = (t5 == ALUByteFunction_Dpb) ? 1 : 0;   

force_alignment32508:
  if (_trace) printf("force_alignment32508:\n");
  if (t4 == 0) 
    goto basic_dispatch32505;
  /* Here if argument ALUByteFunctionDpb */
  t6 = t6 << (t3 & 63);   		// Position mask 

basic_dispatch32504:
  if (_trace) printf("basic_dispatch32504:\n");
  t7 = t7 & t6;		// rotated&mask 
  t2 = t2 & ~t6;		// background&~mask 
  t7 = t7 | t2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  *(u32 *)(iSP + 8) = t7;   
  *(u32 *)(iSP + 12) = t8;   		// write the stack cache 
  iSP = iSP + 8;
  goto cachevalid;   

i_block_n_read_shift32484:
  if (_trace) printf("i_block_n_read_shift32484:\n");
  arg5 = t2;
  arg2 = 23;
  goto illegaloperand;

basic_dispatch32505:
  if (_trace) printf("basic_dispatch32505:\n");
  t4 = (t5 == ALUByteFunction_Ldb) ? 1 : 0;   

force_alignment32509:
  if (_trace) printf("force_alignment32509:\n");
  if (t4 != 0)   
    goto basic_dispatch32504;
  goto basic_dispatch32504;   

basic_dispatch32499:
  if (_trace) printf("basic_dispatch32499:\n");
  t5 = (t2 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force_alignment32510:
  if (_trace) printf("force_alignment32510:\n");
  if (t5 == 0) 
    goto basic_dispatch32500;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t2 = *(u64 *)&(processor->rotatelatch);   
  goto basic_dispatch32498;   

basic_dispatch32500:
  if (_trace) printf("basic_dispatch32500:\n");
  t5 = (t2 == ALUByteBackground_Zero) ? 1 : 0;   

force_alignment32511:
  if (_trace) printf("force_alignment32511:\n");
  if (t5 == 0) 
    goto basic_dispatch32498;
  /* Here if argument ALUByteBackgroundZero */
  t2 = zero;
  goto basic_dispatch32498;   

vma_memory_read32487:
  if (_trace) printf("vma_memory_read32487:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t7 = *(s32 *)t9;   
  t8 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma_memory_read32486;   

vma_memory_read32489:
  if (_trace) printf("vma_memory_read32489:\n");

vma_memory_read32488:
  if (_trace) printf("vma_memory_read32488:\n");
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t12 = (t12 * 4) + ivory;   
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);   
  /* TagType. */
  t11 = t8 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t2;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma_memory_read32494:
  if (_trace) printf("vma_memory_read32494:\n");
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0) 
    goto vma_memory_read32493;
  t2 = (u32)t7;   		// Do the indirect thing 
  goto vma_memory_read32485;   

vma_memory_read32493:
  if (_trace) printf("vma_memory_read32493:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma_memory_read32492;
  t8 = t8 & ~63L;
  t8 = t8 | Type_ExternalValueCellPointer;
  goto vma_memory_read32496;   

vma_memory_read32492:

vma_memory_read32491:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock1ReadShift */
/* start DoBlock0ReadAlu */

  /* Halfword operand from stack instruction - DoBlock0ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock0readalu:
  if (_trace) printf("doblock0readalu:\n");

DoBlock0ReadAluSP:
  if (_trace) printf("DoBlock0ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock0ReadAluLP:
  if (_trace) printf("DoBlock0ReadAluLP:\n");

DoBlock0ReadAluFP:
  if (_trace) printf("DoBlock0ReadAluFP:\n");

begindoblock0readalu:
  if (_trace) printf("begindoblock0readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar0;   
  goto blockreadalu;   

DoBlock0ReadAluIM:
  goto doistageerror;

/* end DoBlock0ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock0ReadAlu */
/* start DoBlock3ReadAlu */

  /* Halfword operand from stack instruction - DoBlock3ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock3readalu:
  if (_trace) printf("doblock3readalu:\n");

DoBlock3ReadAluSP:
  if (_trace) printf("DoBlock3ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock3ReadAluLP:
  if (_trace) printf("DoBlock3ReadAluLP:\n");

DoBlock3ReadAluFP:
  if (_trace) printf("DoBlock3ReadAluFP:\n");

begindoblock3readalu:
  if (_trace) printf("begindoblock3readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar3;   
  goto blockreadalu;   

DoBlock3ReadAluIM:
  goto doistageerror;

/* end DoBlock3ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock3ReadAlu */
/* start DoBlock2ReadAlu */

  /* Halfword operand from stack instruction - DoBlock2ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock2readalu:
  if (_trace) printf("doblock2readalu:\n");

DoBlock2ReadAluSP:
  if (_trace) printf("DoBlock2ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock2ReadAluLP:
  if (_trace) printf("DoBlock2ReadAluLP:\n");

DoBlock2ReadAluFP:
  if (_trace) printf("DoBlock2ReadAluFP:\n");

begindoblock2readalu:
  if (_trace) printf("begindoblock2readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar2;   
  goto blockreadalu;   

DoBlock2ReadAluIM:
  goto doistageerror;

/* end DoBlock2ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock2ReadAlu */
/* start DoBlock1ReadAlu */

  /* Halfword operand from stack instruction - DoBlock1ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock1readalu:
  if (_trace) printf("doblock1readalu:\n");

DoBlock1ReadAluSP:
  if (_trace) printf("DoBlock1ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock1ReadAluLP:
  if (_trace) printf("DoBlock1ReadAluLP:\n");

DoBlock1ReadAluFP:
  if (_trace) printf("DoBlock1ReadAluFP:\n");

begindoblock1readalu:
  if (_trace) printf("begindoblock1readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar1;   

blockreadalu:
  if (_trace) printf("blockreadalu:\n");
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  t1 = *(s32 *)arg2;   		// Get the vma 
  t5 = *(s32 *)arg1;   
  t4 = *(s32 *)(arg1 + 4);   
  t5 = (u32)t5;   
  t9 = t4 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i_block_n_read_alu32512;
  t1 = (u32)t1;   
  /* Memory Read Internal */

vma_memory_read32514:
  t11 = t1 + ivory;
  t3 = (t11 * 4);   
  t2 = LDQ_U(t11);   
  t9 = t1 - arg5;   		// Stack cache offset 
  t12 = *(u64 *)&(processor->dataread_mask);   
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;   		// In range? 
  t3 = *(s32 *)t3;   
  t2 = (u8)(t2 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma_memory_read32516;

vma_memory_read32515:
  t11 = zero + 240;   
  t12 = t12 >> (t2 & 63);   
  t11 = t11 >> (t2 & 63);   
  t3 = (u32)t3;   
  if (t12 & 1)   
    goto vma_memory_read32518;

vma_memory_read32525:
  t9 = t2 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i_block_n_read_alu32513;
  t1 = t1 + 1;		// Increment the address 
  *(u32 *)arg2 = t1;   		// Store updated vma in BAR 
  t6 = *(u64 *)&(processor->aluop);   
  *(u64 *)&processor->aluoverflow = zero;   
  t7 = *(u64 *)&(processor->aluandrotatecontrol);   
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;   

force_alignment32586:
  if (_trace) printf("force_alignment32586:\n");
  if (t1 == 0) 
    goto basic_dispatch32527;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;   
  t8 = t8 & 15;		// Extract the ALU boolean function 
  t1 = (t8 == Boole_Clear) ? 1 : 0;   

force_alignment32546:
  if (_trace) printf("force_alignment32546:\n");
  if (t1 != 0)   
    goto basic_dispatch32528;

basic_dispatch32529:
  if (_trace) printf("basic_dispatch32529:\n");
  t1 = (t8 == Boole_And) ? 1 : 0;   

force_alignment32547:
  if (_trace) printf("force_alignment32547:\n");
  if (t1 == 0) 
    goto basic_dispatch32530;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto basic_dispatch32528;   

basic_dispatch32530:
  if (_trace) printf("basic_dispatch32530:\n");
  t1 = (t8 == Boole_AndC1) ? 1 : 0;   

force_alignment32548:
  if (_trace) printf("force_alignment32548:\n");
  if (t1 == 0) 
    goto basic_dispatch32531;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto basic_dispatch32528;   

basic_dispatch32531:
  if (_trace) printf("basic_dispatch32531:\n");
  t1 = (t8 == Boole_2) ? 1 : 0;   

force_alignment32549:
  if (_trace) printf("force_alignment32549:\n");
  if (t1 == 0) 
    goto basic_dispatch32532;
  /* Here if argument Boole2 */
  t8 = t5;
  goto basic_dispatch32528;   

basic_dispatch32532:
  if (_trace) printf("basic_dispatch32532:\n");
  t1 = (t8 == Boole_AndC2) ? 1 : 0;   

force_alignment32550:
  if (_trace) printf("force_alignment32550:\n");
  if (t1 == 0) 
    goto basic_dispatch32533;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto basic_dispatch32528;   

basic_dispatch32533:
  if (_trace) printf("basic_dispatch32533:\n");
  t1 = (t8 == Boole_1) ? 1 : 0;   

force_alignment32551:
  if (_trace) printf("force_alignment32551:\n");
  if (t1 == 0) 
    goto basic_dispatch32534;
  /* Here if argument Boole1 */
  t8 = t3;
  goto basic_dispatch32528;   

basic_dispatch32534:
  if (_trace) printf("basic_dispatch32534:\n");
  t1 = (t8 == Boole_Xor) ? 1 : 0;   

force_alignment32552:
  if (_trace) printf("force_alignment32552:\n");
  if (t1 == 0) 
    goto basic_dispatch32535;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;   
  goto basic_dispatch32528;   

basic_dispatch32535:
  if (_trace) printf("basic_dispatch32535:\n");
  t1 = (t8 == Boole_Ior) ? 1 : 0;   

force_alignment32553:
  if (_trace) printf("force_alignment32553:\n");
  if (t1 == 0) 
    goto basic_dispatch32536;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto basic_dispatch32528;   

basic_dispatch32536:
  if (_trace) printf("basic_dispatch32536:\n");
  t1 = (t8 == Boole_Nor) ? 1 : 0;   

force_alignment32554:
  if (_trace) printf("force_alignment32554:\n");
  if (t1 == 0) 
    goto basic_dispatch32537;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;   
  goto basic_dispatch32528;   

basic_dispatch32537:
  if (_trace) printf("basic_dispatch32537:\n");
  t1 = (t8 == Boole_Equiv) ? 1 : 0;   

force_alignment32555:
  if (_trace) printf("force_alignment32555:\n");
  if (t1 == 0) 
    goto basic_dispatch32538;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;   
  t8 = ~t8;   
  goto basic_dispatch32528;   

basic_dispatch32538:
  if (_trace) printf("basic_dispatch32538:\n");
  t1 = (t8 == Boole_C1) ? 1 : 0;   

force_alignment32556:
  if (_trace) printf("force_alignment32556:\n");
  if (t1 == 0) 
    goto basic_dispatch32539;
  /* Here if argument BooleC1 */
  t8 = ~t3;   
  goto basic_dispatch32528;   

basic_dispatch32539:
  if (_trace) printf("basic_dispatch32539:\n");
  t1 = (t8 == Boole_OrC1) ? 1 : 0;   

force_alignment32557:
  if (_trace) printf("force_alignment32557:\n");
  if (t1 == 0) 
    goto basic_dispatch32540;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);   
  goto basic_dispatch32528;   

basic_dispatch32540:
  if (_trace) printf("basic_dispatch32540:\n");
  t1 = (t8 == Boole_C2) ? 1 : 0;   

force_alignment32558:
  if (_trace) printf("force_alignment32558:\n");
  if (t1 == 0) 
    goto basic_dispatch32541;
  /* Here if argument BooleC2 */
  t8 = ~t5;   
  goto basic_dispatch32528;   

basic_dispatch32541:
  if (_trace) printf("basic_dispatch32541:\n");
  t1 = (t8 == Boole_OrC2) ? 1 : 0;   

force_alignment32559:
  if (_trace) printf("force_alignment32559:\n");
  if (t1 == 0) 
    goto basic_dispatch32542;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto basic_dispatch32528;   

basic_dispatch32542:
  if (_trace) printf("basic_dispatch32542:\n");
  t1 = (t8 == Boole_Nand) ? 1 : 0;   

force_alignment32560:
  if (_trace) printf("force_alignment32560:\n");
  if (t1 == 0) 
    goto basic_dispatch32543;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto basic_dispatch32528;   

basic_dispatch32543:
  if (_trace) printf("basic_dispatch32543:\n");
  t1 = (t8 == Boole_Set) ? 1 : 0;   

force_alignment32561:
  if (_trace) printf("force_alignment32561:\n");
  if (t1 == 0) 
    goto basic_dispatch32528;
  /* Here if argument BooleSet */
  t8 = ~zero;   

basic_dispatch32528:
  if (_trace) printf("basic_dispatch32528:\n");
  *(u32 *)arg1 = t8;   
  goto NEXTINSTRUCTION;   

basic_dispatch32527:
  if (_trace) printf("basic_dispatch32527:\n");
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;   

force_alignment32587:
  if (_trace) printf("force_alignment32587:\n");
  if (t1 == 0) 
    goto basic_dispatch32562;
  /* Here if argument ALUFunctionByte */
  t9 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t10 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t1 = t7 >> 10;   
  t1 = t1 & 3;		// Extract the byte background 
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;   

force_alignment32569:
  if (_trace) printf("force_alignment32569:\n");
  if (t11 == 0) 
    goto basic_dispatch32565;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

basic_dispatch32564:
  if (_trace) printf("basic_dispatch32564:\n");
  t12 = t7 >> 12;   
  t12 = t12 & 1;		// Extractthe byte rotate latch 
  t8 = t5 << (t9 & 63);   
  t11 = (u32)(t8 >> ((4&7)*8));   
  t8 = (u32)t8;   
  t8 = t8 | t11;		// OP2 rotated 
  if (t12 == 0) 		// Don't update rotate latch if not requested 
    goto alu_function_byte32563;
  *(u64 *)&processor->rotatelatch = t8;   

alu_function_byte32563:
  if (_trace) printf("alu_function_byte32563:\n");
  t12 = zero + -2;   
  t12 = t12 << (t10 & 63);   
  t12 = ~t12;   		// Compute mask 
  /* Get byte function */
  t11 = t7 >> 13;   
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;   

force_alignment32574:
  if (_trace) printf("force_alignment32574:\n");
  if (t10 == 0) 
    goto basic_dispatch32571;
  /* Here if argument ALUByteFunctionDpb */
  t12 = t12 << (t9 & 63);   		// Position mask 

basic_dispatch32570:
  if (_trace) printf("basic_dispatch32570:\n");
  t8 = t8 & t12;		// rotated&mask 
  t1 = t1 & ~t12;		// background&~mask 
  t8 = t8 | t1;
  *(u32 *)arg1 = t8;   
  goto NEXTINSTRUCTION;   

basic_dispatch32562:
  if (_trace) printf("basic_dispatch32562:\n");
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;   

force_alignment32588:
  if (_trace) printf("force_alignment32588:\n");
  if (t1 == 0) 
    goto basic_dispatch32575;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;   
  t10 = t10 & 3;		// Extract the op2 
  t9 = t7 >> 10;   
  t9 = t9 & 1;		// Extract the adder carry in 
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;   

force_alignment32583:
  if (_trace) printf("force_alignment32583:\n");
  if (t11 == 0) 
    goto basic_dispatch32578;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

basic_dispatch32577:
  if (_trace) printf("basic_dispatch32577:\n");
  t8 = t3 + t1;
  t8 = t8 + t9;
  t10 = t8 >> 31;   		// Sign bit 
  t11 = t8 >> 32;   		// Next bit 
  t10 = t10 ^ t11;   		// Low bit is now overflow indicator 
  t11 = t7 >> 24;   		// Get the load-carry-in bit 
  *(u64 *)&processor->aluoverflow = t10;   
  if ((t11 & 1) == 0)   
    goto alu_function_adder32576;
  t10 = (u32)(t8 >> ((4&7)*8));   		// Get the carry 
  t11 = zero + 1024;   
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;   
  t7 = t7 | t11;		// Set the adder carry in 
  *(u64 *)&processor->aluandrotatecontrol = t7;   

alu_function_adder32576:
  if (_trace) printf("alu_function_adder32576:\n");
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->aluborrow = t10;   
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->alulessthan = t10;   
  *(u32 *)arg1 = t8;   
  goto NEXTINSTRUCTION;   

basic_dispatch32575:
  if (_trace) printf("basic_dispatch32575:\n");
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;   

force_alignment32589:
  if (_trace) printf("force_alignment32589:\n");
  if (t1 == 0) 
    goto basic_dispatch32526;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;
  *(u32 *)arg1 = t8;   
  goto NEXTINSTRUCTION;   

basic_dispatch32526:
  if (_trace) printf("basic_dispatch32526:\n");

i_block_n_read_alu32512:
  if (_trace) printf("i_block_n_read_alu32512:\n");
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);   
  t9 = arg1 - t9;   		// stack cache base relative offset 
  t9 = t9 >> 3;   		// convert byte address to word address 
  t1 = t9 + arg5;		// reconstruct VMA 
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

i_block_n_read_alu32513:
  if (_trace) printf("i_block_n_read_alu32513:\n");
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

basic_dispatch32578:
  if (_trace) printf("basic_dispatch32578:\n");
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;   

force_alignment32590:
  if (_trace) printf("force_alignment32590:\n");
  if (t11 == 0) 
    goto basic_dispatch32579;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto basic_dispatch32577;   

basic_dispatch32579:
  if (_trace) printf("basic_dispatch32579:\n");
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;   

force_alignment32591:
  if (_trace) printf("force_alignment32591:\n");
  if (t11 == 0) 
    goto basic_dispatch32580;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;   
  t1 = (u32)t1;   
  goto basic_dispatch32577;   

basic_dispatch32580:
  if (_trace) printf("basic_dispatch32580:\n");
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;   

force_alignment32592:
  if (_trace) printf("force_alignment32592:\n");
  if (t11 == 0) 
    goto basic_dispatch32577;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;   
  t1 = (u32)t1;   
  goto basic_dispatch32577;   

basic_dispatch32571:
  if (_trace) printf("basic_dispatch32571:\n");
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;   

force_alignment32593:
  if (_trace) printf("force_alignment32593:\n");
  if (t10 != 0)   
    goto basic_dispatch32570;
  goto basic_dispatch32570;   

basic_dispatch32565:
  if (_trace) printf("basic_dispatch32565:\n");
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force_alignment32594:
  if (_trace) printf("force_alignment32594:\n");
  if (t11 == 0) 
    goto basic_dispatch32566;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);   
  goto basic_dispatch32564;   

basic_dispatch32566:
  if (_trace) printf("basic_dispatch32566:\n");
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;   

force_alignment32595:
  if (_trace) printf("force_alignment32595:\n");
  if (t11 == 0) 
    goto basic_dispatch32564;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto basic_dispatch32564;   

vma_memory_read32516:
  if (_trace) printf("vma_memory_read32516:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t3 = *(s32 *)t9;   
  t2 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma_memory_read32515;   

vma_memory_read32518:
  if (_trace) printf("vma_memory_read32518:\n");
  if ((t11 & 1) == 0)   
    goto vma_memory_read32517;
  t1 = (u32)t3;   		// Do the indirect thing 
  goto vma_memory_read32514;   

vma_memory_read32517:
  if (_trace) printf("vma_memory_read32517:\n");
  t12 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t11 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t1;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma_memory_read32522:
  if (_trace) printf("vma_memory_read32522:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma_memory_read32521;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma_memory_read32525;   

vma_memory_read32521:

vma_memory_read32520:
  /* Perform memory action */
  arg1 = t12;
  arg2 = 0;
  goto performmemoryaction;

DoBlock1ReadAluIM:
  goto doistageerror;

/* end DoBlock1ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock1ReadAlu */
/* start DoBlock0ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadTest */

doblock0readtest:
  if (_trace) printf("doblock0readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadTestIM:
  if (_trace) printf("DoBlock0ReadTestIM:\n");

DoBlock0ReadTestSP:
  if (_trace) printf("DoBlock0ReadTestSP:\n");

DoBlock0ReadTestLP:
  if (_trace) printf("DoBlock0ReadTestLP:\n");

DoBlock0ReadTestFP:
  if (_trace) printf("DoBlock0ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockreadtest;   

/* end DoBlock0ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock0ReadTest */
/* start DoBlock3ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadTest */

doblock3readtest:
  if (_trace) printf("doblock3readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock3ReadTestIM:
  if (_trace) printf("DoBlock3ReadTestIM:\n");

DoBlock3ReadTestSP:
  if (_trace) printf("DoBlock3ReadTestSP:\n");

DoBlock3ReadTestLP:
  if (_trace) printf("DoBlock3ReadTestLP:\n");

DoBlock3ReadTestFP:
  if (_trace) printf("DoBlock3ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;   
  goto blockreadtest;   

/* end DoBlock3ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock3ReadTest */
/* start DoBlock2ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadTest */

doblock2readtest:
  if (_trace) printf("doblock2readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock2ReadTestIM:
  if (_trace) printf("DoBlock2ReadTestIM:\n");

DoBlock2ReadTestSP:
  if (_trace) printf("DoBlock2ReadTestSP:\n");

DoBlock2ReadTestLP:
  if (_trace) printf("DoBlock2ReadTestLP:\n");

DoBlock2ReadTestFP:
  if (_trace) printf("DoBlock2ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;   
  goto blockreadtest;   

/* end DoBlock2ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock2ReadTest */
/* start DoBlock1ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadTest */

doblock1readtest:
  if (_trace) printf("doblock1readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock1ReadTestIM:
  if (_trace) printf("DoBlock1ReadTestIM:\n");

DoBlock1ReadTestSP:
  if (_trace) printf("DoBlock1ReadTestSP:\n");

DoBlock1ReadTestLP:
  if (_trace) printf("DoBlock1ReadTestLP:\n");

DoBlock1ReadTestFP:
  if (_trace) printf("DoBlock1ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;   

blockreadtest:
  if (_trace) printf("blockreadtest:\n");
  arg3 = *(s32 *)arg2;   		// Get the vma 
  t1 = arg1 >> 6;   		// cycle type 
  t5 = *(s32 *)iSP;   
  t4 = *(s32 *)(iSP + 4);   
  t5 = (u32)t5;   
  arg3 = (u32)arg3;   
  /* Memory Read Internal */

vma_memory_read32602:
  t9 = *(u64 *)&(processor->stackcachebasevma);   		// Base of stack cache 
  t11 = arg3 + ivory;
  t10 = *(s32 *)&processor->scovlimit;   
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t2 = LDQ_U(t11);   
  t12 = (t12 * 4) + ivory;   
  t3 = (t11 * 4);   
  t9 = arg3 - t9;   		// Stack cache offset 
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);   
  t10 = ((u64)t9 < (u64)t10) ? 1 : 0;   		// In range? 
  t3 = *(s32 *)t3;   
  t2 = (u8)(t2 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma_memory_read32604;

vma_memory_read32603:
  t12 = t12 >> (t2 & 63);   
  t3 = (u32)t3;   
  if (t12 & 1)   
    goto vma_memory_read32606;

vma_memory_read32613:
  t1 = arg1 & 32;		// =fixnum onlyp 
  if (t1 == 0) 		// J. if we don't have to test for fixnump. 
    goto i_block_n_read_test32596;
  t9 = t2 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i_block_n_read_test32599;
  t9 = t4 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i_block_n_read_test32600;

i_block_n_read_test32596:
  if (_trace) printf("i_block_n_read_test32596:\n");
  t1 = arg1 & 16;		// =cdr-code-nextp 
  if (t1 == 0) 		// J. if we don't have to clear CDR codes. 
    goto i_block_n_read_test32598;
  /* TagType. */
  t2 = t2 & 63;

i_block_n_read_test32598:
  if (_trace) printf("i_block_n_read_test32598:\n");
  t6 = *(u64 *)&(processor->aluop);   
  *(u64 *)&processor->aluoverflow = zero;   
  t7 = *(u64 *)&(processor->aluandrotatecontrol);   
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;   

force_alignment32674:
  if (_trace) printf("force_alignment32674:\n");
  if (t1 == 0) 
    goto basic_dispatch32615;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;   
  t8 = t8 & 15;		// Extract the ALU boolean function 
  t1 = (t8 == Boole_Clear) ? 1 : 0;   

force_alignment32634:
  if (_trace) printf("force_alignment32634:\n");
  if (t1 != 0)   
    goto basic_dispatch32616;

basic_dispatch32617:
  if (_trace) printf("basic_dispatch32617:\n");
  t1 = (t8 == Boole_And) ? 1 : 0;   

force_alignment32635:
  if (_trace) printf("force_alignment32635:\n");
  if (t1 == 0) 
    goto basic_dispatch32618;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto basic_dispatch32616;   

basic_dispatch32618:
  if (_trace) printf("basic_dispatch32618:\n");
  t1 = (t8 == Boole_AndC1) ? 1 : 0;   

force_alignment32636:
  if (_trace) printf("force_alignment32636:\n");
  if (t1 == 0) 
    goto basic_dispatch32619;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto basic_dispatch32616;   

basic_dispatch32619:
  if (_trace) printf("basic_dispatch32619:\n");
  t1 = (t8 == Boole_2) ? 1 : 0;   

force_alignment32637:
  if (_trace) printf("force_alignment32637:\n");
  if (t1 == 0) 
    goto basic_dispatch32620;
  /* Here if argument Boole2 */
  t8 = t5;
  goto basic_dispatch32616;   

basic_dispatch32620:
  if (_trace) printf("basic_dispatch32620:\n");
  t1 = (t8 == Boole_AndC2) ? 1 : 0;   

force_alignment32638:
  if (_trace) printf("force_alignment32638:\n");
  if (t1 == 0) 
    goto basic_dispatch32621;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto basic_dispatch32616;   

basic_dispatch32621:
  if (_trace) printf("basic_dispatch32621:\n");
  t1 = (t8 == Boole_1) ? 1 : 0;   

force_alignment32639:
  if (_trace) printf("force_alignment32639:\n");
  if (t1 == 0) 
    goto basic_dispatch32622;
  /* Here if argument Boole1 */
  t8 = t3;
  goto basic_dispatch32616;   

basic_dispatch32622:
  if (_trace) printf("basic_dispatch32622:\n");
  t1 = (t8 == Boole_Xor) ? 1 : 0;   

force_alignment32640:
  if (_trace) printf("force_alignment32640:\n");
  if (t1 == 0) 
    goto basic_dispatch32623;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;   
  goto basic_dispatch32616;   

basic_dispatch32623:
  if (_trace) printf("basic_dispatch32623:\n");
  t1 = (t8 == Boole_Ior) ? 1 : 0;   

force_alignment32641:
  if (_trace) printf("force_alignment32641:\n");
  if (t1 == 0) 
    goto basic_dispatch32624;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto basic_dispatch32616;   

basic_dispatch32624:
  if (_trace) printf("basic_dispatch32624:\n");
  t1 = (t8 == Boole_Nor) ? 1 : 0;   

force_alignment32642:
  if (_trace) printf("force_alignment32642:\n");
  if (t1 == 0) 
    goto basic_dispatch32625;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;   
  goto basic_dispatch32616;   

basic_dispatch32625:
  if (_trace) printf("basic_dispatch32625:\n");
  t1 = (t8 == Boole_Equiv) ? 1 : 0;   

force_alignment32643:
  if (_trace) printf("force_alignment32643:\n");
  if (t1 == 0) 
    goto basic_dispatch32626;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;   
  t8 = ~t8;   
  goto basic_dispatch32616;   

basic_dispatch32626:
  if (_trace) printf("basic_dispatch32626:\n");
  t1 = (t8 == Boole_C1) ? 1 : 0;   

force_alignment32644:
  if (_trace) printf("force_alignment32644:\n");
  if (t1 == 0) 
    goto basic_dispatch32627;
  /* Here if argument BooleC1 */
  t8 = ~t3;   
  goto basic_dispatch32616;   

basic_dispatch32627:
  if (_trace) printf("basic_dispatch32627:\n");
  t1 = (t8 == Boole_OrC1) ? 1 : 0;   

force_alignment32645:
  if (_trace) printf("force_alignment32645:\n");
  if (t1 == 0) 
    goto basic_dispatch32628;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);   
  goto basic_dispatch32616;   

basic_dispatch32628:
  if (_trace) printf("basic_dispatch32628:\n");
  t1 = (t8 == Boole_C2) ? 1 : 0;   

force_alignment32646:
  if (_trace) printf("force_alignment32646:\n");
  if (t1 == 0) 
    goto basic_dispatch32629;
  /* Here if argument BooleC2 */
  t8 = ~t5;   
  goto basic_dispatch32616;   

basic_dispatch32629:
  if (_trace) printf("basic_dispatch32629:\n");
  t1 = (t8 == Boole_OrC2) ? 1 : 0;   

force_alignment32647:
  if (_trace) printf("force_alignment32647:\n");
  if (t1 == 0) 
    goto basic_dispatch32630;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto basic_dispatch32616;   

basic_dispatch32630:
  if (_trace) printf("basic_dispatch32630:\n");
  t1 = (t8 == Boole_Nand) ? 1 : 0;   

force_alignment32648:
  if (_trace) printf("force_alignment32648:\n");
  if (t1 == 0) 
    goto basic_dispatch32631;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto basic_dispatch32616;   

basic_dispatch32631:
  if (_trace) printf("basic_dispatch32631:\n");
  t1 = (t8 == Boole_Set) ? 1 : 0;   

force_alignment32649:
  if (_trace) printf("force_alignment32649:\n");
  if (t1 == 0) 
    goto basic_dispatch32616;
  /* Here if argument BooleSet */
  t8 = ~zero;   

basic_dispatch32616:
  if (_trace) printf("basic_dispatch32616:\n");

basic_dispatch32614:
  if (_trace) printf("basic_dispatch32614:\n");
  t1 = t7 >> 16;   
  t1 = t1 & 31;		// Extract ALU condition 
  t10 = *(u64 *)&(processor->aluoverflow);   
  t11 = *(u64 *)&(processor->aluborrow);   
  t12 = *(u64 *)&(processor->alulessthan);   
  t9 = (t1 == ALUCondition_SignedLessThanOrEqual) ? 1 : 0;   

force_alignment32706:
  if (_trace) printf("force_alignment32706:\n");
  if (t9 == 0) 
    goto basic_dispatch32679;
  /* Here if argument ALUConditionSignedLessThanOrEqual */
  if (t12 != 0)   
    goto alu_compute_condition32675;
  if (t8 == 0) 
    goto alu_compute_condition32675;

basic_dispatch32678:
  if (_trace) printf("basic_dispatch32678:\n");

alu_compute_condition32676:
  if (_trace) printf("alu_compute_condition32676:\n");
  t1 = zero;
  goto alu_compute_condition32677;   

alu_compute_condition32675:
  if (_trace) printf("alu_compute_condition32675:\n");
  t1 = 1;

alu_compute_condition32677:
  if (_trace) printf("alu_compute_condition32677:\n");
  t9 = t7 >> 21;   
  t9 = t9 & 1;		// Extract the condition sense 
  t1 = t1 ^ t9;   
  if (t1 != 0)   
    goto i_block_n_read_test32601;
  t1 = arg1 & 4;		// =no-incrementp 
  if (t1 != 0)   		// J. if we don't have to increment the address. 
    goto i_block_n_read_test32597;
  arg3 = arg3 + 1;		// Increment the address 

i_block_n_read_test32597:
  if (_trace) printf("i_block_n_read_test32597:\n");
  *(u32 *)arg2 = arg3;   		// Store updated vma in BAR 
  goto NEXTINSTRUCTION;   

i_block_n_read_test32601:
  if (_trace) printf("i_block_n_read_test32601:\n");
  t10 = *(s32 *)(iSP + -8);   
  t9 = *(s32 *)(iSP + -4);   
  t10 = (u32)t10;   
  t10 = t10 << 1;   
  iPC = t9 & 1;
  iPC = iPC + t10;
  goto interpretinstructionforjump;   

i_block_n_read_test32600:
  if (_trace) printf("i_block_n_read_test32600:\n");
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);   
  arg3 = *(u64 *)&(processor->stackcachebasevma);   
  t9 = iSP - t9;   		// stack cache base relative offset 
  t9 = t9 >> 3;   		// convert byte address to word address 
  arg3 = t9 + arg3;		// reconstruct VMA 
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

i_block_n_read_test32599:
  if (_trace) printf("i_block_n_read_test32599:\n");
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

basic_dispatch32679:
  if (_trace) printf("basic_dispatch32679:\n");
  t9 = (t1 == ALUCondition_SignedLessThan) ? 1 : 0;   

force_alignment32707:
  if (_trace) printf("force_alignment32707:\n");
  if (t9 == 0) 
    goto basic_dispatch32680;
  /* Here if argument ALUConditionSignedLessThan */
  if (t12 != 0)   
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32680:
  if (_trace) printf("basic_dispatch32680:\n");
  t9 = (t1 == ALUCondition_Negative) ? 1 : 0;   

force_alignment32708:
  if (_trace) printf("force_alignment32708:\n");
  if (t9 == 0) 
    goto basic_dispatch32681;
  /* Here if argument ALUConditionNegative */
  if ((s64)t8 < 0)   
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32681:
  if (_trace) printf("basic_dispatch32681:\n");
  t9 = (t1 == ALUCondition_SignedOverflow) ? 1 : 0;   

force_alignment32709:
  if (_trace) printf("force_alignment32709:\n");
  if (t9 == 0) 
    goto basic_dispatch32682;
  /* Here if argument ALUConditionSignedOverflow */
  if (t10 != 0)   
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32682:
  if (_trace) printf("basic_dispatch32682:\n");
  t9 = (t1 == ALUCondition_UnsignedLessThanOrEqual) ? 1 : 0;   

force_alignment32710:
  if (_trace) printf("force_alignment32710:\n");
  if (t9 == 0) 
    goto basic_dispatch32683;
  /* Here if argument ALUConditionUnsignedLessThanOrEqual */
  if (t11 != 0)   
    goto alu_compute_condition32675;
  if (t8 == 0) 
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32683:
  if (_trace) printf("basic_dispatch32683:\n");
  t9 = (t1 == ALUCondition_UnsignedLessThan) ? 1 : 0;   

force_alignment32711:
  if (_trace) printf("force_alignment32711:\n");
  if (t9 == 0) 
    goto basic_dispatch32684;
  /* Here if argument ALUConditionUnsignedLessThan */
  if (t11 != 0)   
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32684:
  if (_trace) printf("basic_dispatch32684:\n");
  t9 = (t1 == ALUCondition_Zero) ? 1 : 0;   

force_alignment32712:
  if (_trace) printf("force_alignment32712:\n");
  if (t9 == 0) 
    goto basic_dispatch32685;
  /* Here if argument ALUConditionZero */
  if (t8 == 0) 
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32685:
  if (_trace) printf("basic_dispatch32685:\n");
  t9 = (t1 == ALUCondition_High25Zero) ? 1 : 0;   

force_alignment32713:
  if (_trace) printf("force_alignment32713:\n");
  if (t9 == 0) 
    goto basic_dispatch32686;
  /* Here if argument ALUConditionHigh25Zero */
  t1 = t8 >> 7;   
  if (t1 == 0) 
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32686:
  if (_trace) printf("basic_dispatch32686:\n");
  t9 = (t1 == ALUCondition_Eq) ? 1 : 0;   

force_alignment32714:
  if (_trace) printf("force_alignment32714:\n");
  if (t9 == 0) 
    goto basic_dispatch32687;
  /* Here if argument ALUConditionEq */
  if (t8 != 0)   
    goto alu_compute_condition32676;
  t9 = t2 ^ t4;   
  /* TagType. */
  t9 = t9 & 63;
  if (t9 == 0) 
    goto alu_compute_condition32675;
  goto basic_dispatch32678;   

basic_dispatch32687:
  if (_trace) printf("basic_dispatch32687:\n");
  t9 = (t1 == ALUCondition_Op1Ephemeralp) ? 1 : 0;   

force_alignment32715:
  if (_trace) printf("force_alignment32715:\n");
  if (t9 == 0) 
    goto basic_dispatch32688;
  /* Here if argument ALUConditionOp1Ephemeralp */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32688:
  if (_trace) printf("basic_dispatch32688:\n");
  t9 = (t1 == ALUCondition_ResultTypeNil) ? 1 : 0;   

force_alignment32716:
  if (_trace) printf("force_alignment32716:\n");
  if (t9 == 0) 
    goto basic_dispatch32689;
  /* Here if argument ALUConditionResultTypeNil */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32689:
  if (_trace) printf("basic_dispatch32689:\n");
  t9 = (t1 == ALUCondition_Op2Fixnum) ? 1 : 0;   

force_alignment32717:
  if (_trace) printf("force_alignment32717:\n");
  if (t9 == 0) 
    goto basic_dispatch32690;
  /* Here if argument ALUConditionOp2Fixnum */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32690:
  if (_trace) printf("basic_dispatch32690:\n");
  t9 = (t1 == ALUCondition_False) ? 1 : 0;   

force_alignment32718:
  if (_trace) printf("force_alignment32718:\n");
  if (t9 == 0) 
    goto basic_dispatch32691;
  /* Here if argument ALUConditionFalse */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32691:
  if (_trace) printf("basic_dispatch32691:\n");
  t9 = (t1 == ALUCondition_ResultCdrLow) ? 1 : 0;   

force_alignment32719:
  if (_trace) printf("force_alignment32719:\n");
  if (t9 == 0) 
    goto basic_dispatch32692;
  /* Here if argument ALUConditionResultCdrLow */
  /* TagCdr. */
  t9 = t2 >> 6;   
  t1 = t9 & 1;
  goto alu_compute_condition32677;   

basic_dispatch32692:
  if (_trace) printf("basic_dispatch32692:\n");
  t9 = (t1 == ALUCondition_CleanupBitsSet) ? 1 : 0;   

force_alignment32720:
  if (_trace) printf("force_alignment32720:\n");
  if (t9 == 0) 
    goto basic_dispatch32693;
  /* Here if argument ALUConditionCleanupBitsSet */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32693:
  if (_trace) printf("basic_dispatch32693:\n");
  t9 = (t1 == ALUCondition_AddressInStackCache) ? 1 : 0;   

force_alignment32721:
  if (_trace) printf("force_alignment32721:\n");
  if (t9 == 0) 
    goto basic_dispatch32694;
  /* Here if argument ALUConditionAddressInStackCache */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32694:
  if (_trace) printf("basic_dispatch32694:\n");
  t9 = (t1 == ALUCondition_ExtraStackMode) ? 1 : 0;   

force_alignment32722:
  if (_trace) printf("force_alignment32722:\n");
  if (t9 == 0) 
    goto basic_dispatch32695;
  /* Here if argument ALUConditionExtraStackMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32695:
  if (_trace) printf("basic_dispatch32695:\n");
  t9 = (t1 == ALUCondition_FepMode) ? 1 : 0;   

force_alignment32723:
  if (_trace) printf("force_alignment32723:\n");
  if (t9 == 0) 
    goto basic_dispatch32696;
  /* Here if argument ALUConditionFepMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32696:
  if (_trace) printf("basic_dispatch32696:\n");
  t9 = (t1 == ALUCondition_FpCoprocessorPresent) ? 1 : 0;   

force_alignment32724:
  if (_trace) printf("force_alignment32724:\n");
  if (t9 == 0) 
    goto basic_dispatch32697;
  /* Here if argument ALUConditionFpCoprocessorPresent */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32697:
  if (_trace) printf("basic_dispatch32697:\n");
  t9 = (t1 == ALUCondition_Op1Oldspacep) ? 1 : 0;   

force_alignment32725:
  if (_trace) printf("force_alignment32725:\n");
  if (t9 == 0) 
    goto basic_dispatch32698;
  /* Here if argument ALUConditionOp1Oldspacep */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32698:
  if (_trace) printf("basic_dispatch32698:\n");
  t9 = (t1 == ALUCondition_PendingSequenceBreakEnabled) ? 1 : 0;   

force_alignment32726:
  if (_trace) printf("force_alignment32726:\n");
  if (t9 == 0) 
    goto basic_dispatch32699;
  /* Here if argument ALUConditionPendingSequenceBreakEnabled */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32699:
  if (_trace) printf("basic_dispatch32699:\n");
  t9 = (t1 == ALUCondition_Op1TypeAcceptable) ? 1 : 0;   

force_alignment32727:
  if (_trace) printf("force_alignment32727:\n");
  if (t9 == 0) 
    goto basic_dispatch32700;
  /* Here if argument ALUConditionOp1TypeAcceptable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32700:
  if (_trace) printf("basic_dispatch32700:\n");
  t9 = (t1 == ALUCondition_Op1TypeCondition) ? 1 : 0;   

force_alignment32728:
  if (_trace) printf("force_alignment32728:\n");
  if (t9 == 0) 
    goto basic_dispatch32701;
  /* Here if argument ALUConditionOp1TypeCondition */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32701:
  if (_trace) printf("basic_dispatch32701:\n");
  t9 = (t1 == ALUCondition_StackCacheOverflow) ? 1 : 0;   

force_alignment32729:
  if (_trace) printf("force_alignment32729:\n");
  if (t9 == 0) 
    goto basic_dispatch32702;
  /* Here if argument ALUConditionStackCacheOverflow */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32702:
  if (_trace) printf("basic_dispatch32702:\n");
  t9 = (t1 == ALUCondition_OrLogicVariable) ? 1 : 0;   

force_alignment32730:
  if (_trace) printf("force_alignment32730:\n");
  if (t9 == 0) 
    goto basic_dispatch32703;
  /* Here if argument ALUConditionOrLogicVariable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32703:
  if (_trace) printf("basic_dispatch32703:\n");
  /* Here for all other cases */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32615:
  if (_trace) printf("basic_dispatch32615:\n");
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;   

force_alignment32731:
  if (_trace) printf("force_alignment32731:\n");
  if (t1 == 0) 
    goto basic_dispatch32650;
  /* Here if argument ALUFunctionByte */
  t9 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t10 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t1 = t7 >> 10;   
  t1 = t1 & 3;		// Extract the byte background 
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;   

force_alignment32657:
  if (_trace) printf("force_alignment32657:\n");
  if (t11 == 0) 
    goto basic_dispatch32653;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

basic_dispatch32652:
  if (_trace) printf("basic_dispatch32652:\n");
  t12 = t7 >> 12;   
  t12 = t12 & 1;		// Extractthe byte rotate latch 
  t8 = t5 << (t9 & 63);   
  t11 = (u32)(t8 >> ((4&7)*8));   
  t8 = (u32)t8;   
  t8 = t8 | t11;		// OP2 rotated 
  if (t12 == 0) 		// Don't update rotate latch if not requested 
    goto alu_function_byte32651;
  *(u64 *)&processor->rotatelatch = t8;   

alu_function_byte32651:
  if (_trace) printf("alu_function_byte32651:\n");
  t12 = zero + -2;   
  t12 = t12 << (t10 & 63);   
  t12 = ~t12;   		// Compute mask 
  /* Get byte function */
  t11 = t7 >> 13;   
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;   

force_alignment32662:
  if (_trace) printf("force_alignment32662:\n");
  if (t10 == 0) 
    goto basic_dispatch32659;
  /* Here if argument ALUByteFunctionDpb */
  t12 = t12 << (t9 & 63);   		// Position mask 

basic_dispatch32658:
  if (_trace) printf("basic_dispatch32658:\n");
  t8 = t8 & t12;		// rotated&mask 
  t1 = t1 & ~t12;		// background&~mask 
  t8 = t8 | t1;
  goto basic_dispatch32614;   

basic_dispatch32650:
  if (_trace) printf("basic_dispatch32650:\n");
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;   

force_alignment32732:
  if (_trace) printf("force_alignment32732:\n");
  if (t1 == 0) 
    goto basic_dispatch32663;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;   
  t10 = t10 & 3;		// Extract the op2 
  t9 = t7 >> 10;   
  t9 = t9 & 1;		// Extract the adder carry in 
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;   

force_alignment32671:
  if (_trace) printf("force_alignment32671:\n");
  if (t11 == 0) 
    goto basic_dispatch32666;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

basic_dispatch32665:
  if (_trace) printf("basic_dispatch32665:\n");
  t8 = t3 + t1;
  t8 = t8 + t9;
  t10 = t8 >> 31;   		// Sign bit 
  t11 = t8 >> 32;   		// Next bit 
  t10 = t10 ^ t11;   		// Low bit is now overflow indicator 
  t11 = t7 >> 24;   		// Get the load-carry-in bit 
  *(u64 *)&processor->aluoverflow = t10;   
  if ((t11 & 1) == 0)   
    goto alu_function_adder32664;
  t10 = (u32)(t8 >> ((4&7)*8));   		// Get the carry 
  t11 = zero + 1024;   
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;   
  t7 = t7 | t11;		// Set the adder carry in 
  *(u64 *)&processor->aluandrotatecontrol = t7;   

alu_function_adder32664:
  if (_trace) printf("alu_function_adder32664:\n");
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->aluborrow = t10;   
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->alulessthan = t10;   
  goto basic_dispatch32614;   

basic_dispatch32663:
  if (_trace) printf("basic_dispatch32663:\n");
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;   

force_alignment32733:
  if (_trace) printf("force_alignment32733:\n");
  if (t1 == 0) 
    goto basic_dispatch32614;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic_dispatch32666:
  if (_trace) printf("basic_dispatch32666:\n");
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;   

force_alignment32734:
  if (_trace) printf("force_alignment32734:\n");
  if (t11 == 0) 
    goto basic_dispatch32667;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto basic_dispatch32665;   

basic_dispatch32667:
  if (_trace) printf("basic_dispatch32667:\n");
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;   

force_alignment32735:
  if (_trace) printf("force_alignment32735:\n");
  if (t11 == 0) 
    goto basic_dispatch32668;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;   
  t1 = (u32)t1;   
  goto basic_dispatch32665;   

basic_dispatch32668:
  if (_trace) printf("basic_dispatch32668:\n");
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;   

force_alignment32736:
  if (_trace) printf("force_alignment32736:\n");
  if (t11 == 0) 
    goto basic_dispatch32665;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;   
  t1 = (u32)t1;   
  goto basic_dispatch32665;   

basic_dispatch32659:
  if (_trace) printf("basic_dispatch32659:\n");
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;   

force_alignment32737:
  if (_trace) printf("force_alignment32737:\n");
  if (t10 != 0)   
    goto basic_dispatch32658;
  goto basic_dispatch32658;   

basic_dispatch32653:
  if (_trace) printf("basic_dispatch32653:\n");
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force_alignment32738:
  if (_trace) printf("force_alignment32738:\n");
  if (t11 == 0) 
    goto basic_dispatch32654;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);   
  goto basic_dispatch32652;   

basic_dispatch32654:
  if (_trace) printf("basic_dispatch32654:\n");
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;   

force_alignment32739:
  if (_trace) printf("force_alignment32739:\n");
  if (t11 == 0) 
    goto basic_dispatch32652;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto basic_dispatch32652;   

vma_memory_read32604:
  if (_trace) printf("vma_memory_read32604:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t3 = *(s32 *)t9;   
  t2 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma_memory_read32603;   

vma_memory_read32606:
  if (_trace) printf("vma_memory_read32606:\n");

vma_memory_read32605:
  if (_trace) printf("vma_memory_read32605:\n");
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t12 = (t12 * 4) + ivory;   
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);   
  /* TagType. */
  t11 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg3;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma_memory_read32611:
  if (_trace) printf("vma_memory_read32611:\n");
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0) 
    goto vma_memory_read32610;
  arg3 = (u32)t3;   		// Do the indirect thing 
  goto vma_memory_read32602;   

vma_memory_read32610:
  if (_trace) printf("vma_memory_read32610:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma_memory_read32609;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma_memory_read32613;   

vma_memory_read32609:

vma_memory_read32608:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock1ReadTest */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunblok.as */
