/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * ANY CHANGES MADE TO THIS FILE WILL BE LOST
 *
 * File translated:      ../alpha-emulator/ifunblok.as
 ************************************************************************/

  /* Block Instructions. */
/* start DoBlock0Read */

  /* Halfword 10 bit immediate instruction - DoBlock0Read */

doblock0read:
  if (_trace) printf("doblock0read:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadIM:
  if (_trace) printf("DoBlock0ReadIM:\n");

DoBlock0ReadSP:
  if (_trace) printf("DoBlock0ReadSP:\n");

DoBlock0ReadLP:
  if (_trace) printf("DoBlock0ReadLP:\n");

DoBlock0ReadFP:
  if (_trace) printf("DoBlock0ReadFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockread;   

/* end DoBlock0Read */
  /* End of Halfword operand from stack instruction - DoBlock0Read */
/* start DoBlock0Write */

  /* Halfword operand from stack instruction - DoBlock0Write */

doblock0write:
  if (_trace) printf("doblock0write:\n");
  /* arg2 has the preloaded 8 bit operand. */

DoBlock0WriteIM:
  if (_trace) printf("DoBlock0WriteIM:\n");
  /* This sequence only sucks a moderate amount */
  arg2 = arg2 << 56;   		// sign extend the byte argument. 

force-alignment16290:
  if (_trace) printf("force-alignment16290:\n");
  arg2 = (s64)arg2 >> 56;   		// Rest of sign extension 
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);   
  goto begindoblock0write;   

DoBlock0WriteSP:
  if (_trace) printf("DoBlock0WriteSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock0WriteLP:
  if (_trace) printf("DoBlock0WriteLP:\n");

DoBlock0WriteFP:
  if (_trace) printf("DoBlock0WriteFP:\n");

headdoblock0write:
  if (_trace) printf("headdoblock0write:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoblock0write:
  if (_trace) printf("begindoblock0write:\n");
  /* arg1 has the operand, sign extended if immediate. */
  arg3 = *(s32 *)&processor->bar0;   
  arg2 = (u64)&processor->bar0;   
  goto blockwrite;   

/* end DoBlock0Write */
  /* End of Halfword operand from stack instruction - DoBlock0Write */
/* start DoBlock0ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadShift */

doblock0readshift:
  if (_trace) printf("doblock0readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadShiftIM:
  if (_trace) printf("DoBlock0ReadShiftIM:\n");

DoBlock0ReadShiftSP:
  if (_trace) printf("DoBlock0ReadShiftSP:\n");

DoBlock0ReadShiftLP:
  if (_trace) printf("DoBlock0ReadShiftLP:\n");

DoBlock0ReadShiftFP:
  if (_trace) printf("DoBlock0ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockreadshift;   

/* end DoBlock0ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock0ReadShift */
/* start DoBlock3ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadShift */

doblock3readshift:
  if (_trace) printf("doblock3readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock3ReadShiftIM:
  if (_trace) printf("DoBlock3ReadShiftIM:\n");

DoBlock3ReadShiftSP:
  if (_trace) printf("DoBlock3ReadShiftSP:\n");

DoBlock3ReadShiftLP:
  if (_trace) printf("DoBlock3ReadShiftLP:\n");

DoBlock3ReadShiftFP:
  if (_trace) printf("DoBlock3ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;   
  goto blockreadshift;   

/* end DoBlock3ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock3ReadShift */
/* start DoBlock2ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadShift */

doblock2readshift:
  if (_trace) printf("doblock2readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock2ReadShiftIM:
  if (_trace) printf("DoBlock2ReadShiftIM:\n");

DoBlock2ReadShiftSP:
  if (_trace) printf("DoBlock2ReadShiftSP:\n");

DoBlock2ReadShiftLP:
  if (_trace) printf("DoBlock2ReadShiftLP:\n");

DoBlock2ReadShiftFP:
  if (_trace) printf("DoBlock2ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;   
  goto blockreadshift;   

/* end DoBlock2ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock2ReadShift */
/* start DoBlock1ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadShift */

doblock1readshift:
  if (_trace) printf("doblock1readshift:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock1ReadShiftIM:
  if (_trace) printf("DoBlock1ReadShiftIM:\n");

DoBlock1ReadShiftSP:
  if (_trace) printf("DoBlock1ReadShiftSP:\n");

DoBlock1ReadShiftLP:
  if (_trace) printf("DoBlock1ReadShiftLP:\n");

DoBlock1ReadShiftFP:
  if (_trace) printf("DoBlock1ReadShiftFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;   

blockreadshift:
  if (_trace) printf("blockreadshift:\n");
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  t2 = *(s32 *)arg2;   		// Get the vma 
  t1 = arg1 >> 6;   		// cycle type 
  t4 = arg1 & 4;		// =no-incrementp 
  t5 = arg1 & 16;		// =cdr-code-nextp 
  t6 = arg1 & 32;		// =fixnum onlyp 
  t2 = (u32)t2;   
  /* Memory Read Internal */

vma-memory-read16295:
  t11 = t2 + ivory;
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t8 = LDQ_U(t11);   
  t12 = (t12 * 4) + ivory;   
  t7 = (t11 * 4);   
  t9 = t2 - arg5;   		// Stack cache offset 
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);   
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;   		// In range? 
  t7 = *(s32 *)t7;   
  t8 = (u8)(t8 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma-memory-read16297;

vma-memory-read16296:
  t12 = t12 >> (t8 & 63);   
  t7 = (u32)t7;   
  if (t12 & 1)   
    goto vma-memory-read16299;

vma-memory-read16306:
  if (t6 == 0) 		// J. if we don't have to test for fixnump. 
    goto i%block-n-read-shift16291;
  t9 = t8 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i%block-n-read-shift16294;

i%block-n-read-shift16291:
  if (_trace) printf("i%block-n-read-shift16291:\n");
  if (t4 != 0)   		// J. if we don't have to increment the address. 
    goto i%block-n-read-shift16292;
  t2 = t2 + 1;		// Increment the address 

i%block-n-read-shift16292:
  if (_trace) printf("i%block-n-read-shift16292:\n");
		/* Store updated vma in BAR */
  *(u32 *)arg2 = t2;
  if (t5 == 0) 		// J. if we don't have to clear CDR codes. 
    goto i%block-n-read-shift16293;
  t8 = t8 & 63;

i%block-n-read-shift16293:
  if (_trace) printf("i%block-n-read-shift16293:\n");
  t1 = zero + 21504;   
  t3 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t4 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t2 = t1 >> 10;   
  t2 = t2 & 3;		// Extract the byte background 
  t5 = (t2 == ALUByteBackground_Op1) ? 1 : 0;   

force-alignment16313:
  if (_trace) printf("force-alignment16313:\n");
  if (t5 == 0) 
    goto basic-dispatch16309;
  /* Here if argument ALUByteBackgroundOp1 */
  t2 = t1;

basic-dispatch16308:
  if (_trace) printf("basic-dispatch16308:\n");
  t6 = t1 >> 12;   
  t6 = t6 & 1;		// Extractthe byte rotate latch 
  t7 = t7 << (t3 & 63);   
  t5 = (u32)(t7 >> ((4&7)*8));   
  t7 = (u32)t7;   
  t7 = t7 | t5;		// OP2 rotated 
  if (t6 == 0) 		// Don't update rotate latch if not requested 
    goto alu-function-byte16307;
  *(u64 *)&processor->rotatelatch = t7;   

alu-function-byte16307:
  if (_trace) printf("alu-function-byte16307:\n");
  t6 = zero + -2;   
  t6 = t6 << (t4 & 63);   
  t6 = ~t6;   		// Compute mask 
  /* Get byte function */
  t5 = t1 >> 13;   
  t5 = t5 & 1;
  t4 = (t5 == ALUByteFunction_Dpb) ? 1 : 0;   

force-alignment16318:
  if (_trace) printf("force-alignment16318:\n");
  if (t4 == 0) 
    goto basic-dispatch16315;
  /* Here if argument ALUByteFunctionDpb */
  t6 = t6 << (t3 & 63);   		// Position mask 

basic-dispatch16314:
  if (_trace) printf("basic-dispatch16314:\n");
  t7 = t7 & t6;		// rotated&mask 
  t2 = t2 & ~t6;		// background&~mask 
  t7 = t7 | t2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  *(u32 *)(iSP + 8) = t7;
		/* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto cachevalid;   

i%block-n-read-shift16294:
  if (_trace) printf("i%block-n-read-shift16294:\n");
  arg5 = t2;
  arg2 = 23;
  goto illegaloperand;

basic-dispatch16315:
  if (_trace) printf("basic-dispatch16315:\n");
  t4 = (t5 == ALUByteFunction_Ldb) ? 1 : 0;   

force-alignment16319:
  if (_trace) printf("force-alignment16319:\n");
  if (t4 != 0)   
    goto basic-dispatch16314;
  goto basic-dispatch16314;   

basic-dispatch16309:
  if (_trace) printf("basic-dispatch16309:\n");
  t5 = (t2 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force-alignment16320:
  if (_trace) printf("force-alignment16320:\n");
  if (t5 == 0) 
    goto basic-dispatch16310;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t2 = *(u64 *)&(processor->rotatelatch);   
  goto basic-dispatch16308;   

basic-dispatch16310:
  if (_trace) printf("basic-dispatch16310:\n");
  t5 = (t2 == ALUByteBackground_Zero) ? 1 : 0;   

force-alignment16321:
  if (_trace) printf("force-alignment16321:\n");
  if (t5 == 0) 
    goto basic-dispatch16308;
  /* Here if argument ALUByteBackgroundZero */
  t2 = zero;
  goto basic-dispatch16308;   

vma-memory-read16297:
  if (_trace) printf("vma-memory-read16297:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t7 = *(s32 *)t9;   
  t8 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma-memory-read16296;   

vma-memory-read16299:
  if (_trace) printf("vma-memory-read16299:\n");

vma-memory-read16298:
  if (_trace) printf("vma-memory-read16298:\n");
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t12 = (t12 * 4) + ivory;   
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);   
  /* TagType. */
  t11 = t8 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t2;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma-memory-read16304:
  if (_trace) printf("vma-memory-read16304:\n");
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0) 
    goto vma-memory-read16303;
  t2 = (u32)t7;   		// Do the indirect thing 
  goto vma-memory-read16295;   

vma-memory-read16303:
  if (_trace) printf("vma-memory-read16303:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma-memory-read16302;
  t8 = t8 & ~63L;
  t8 = t8 | Type_ExternalValueCellPointer;
  goto vma-memory-read16306;   

vma-memory-read16302:

vma-memory-read16301:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock1ReadShift */
/* start DoBlock0ReadAlu */

  /* Halfword operand from stack instruction - DoBlock0ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock0readalu:
  if (_trace) printf("doblock0readalu:\n");

DoBlock0ReadAluSP:
  if (_trace) printf("DoBlock0ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock0ReadAluLP:
  if (_trace) printf("DoBlock0ReadAluLP:\n");

DoBlock0ReadAluFP:
  if (_trace) printf("DoBlock0ReadAluFP:\n");

begindoblock0readalu:
  if (_trace) printf("begindoblock0readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar0;   
  goto blockreadalu;   

DoBlock0ReadAluIM:
  goto doistageerror;

/* end DoBlock0ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock0ReadAlu */
/* start DoBlock3ReadAlu */

  /* Halfword operand from stack instruction - DoBlock3ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock3readalu:
  if (_trace) printf("doblock3readalu:\n");

DoBlock3ReadAluSP:
  if (_trace) printf("DoBlock3ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock3ReadAluLP:
  if (_trace) printf("DoBlock3ReadAluLP:\n");

DoBlock3ReadAluFP:
  if (_trace) printf("DoBlock3ReadAluFP:\n");

begindoblock3readalu:
  if (_trace) printf("begindoblock3readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar3;   
  goto blockreadalu;   

DoBlock3ReadAluIM:
  goto doistageerror;

/* end DoBlock3ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock3ReadAlu */
/* start DoBlock2ReadAlu */

  /* Halfword operand from stack instruction - DoBlock2ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock2readalu:
  if (_trace) printf("doblock2readalu:\n");

DoBlock2ReadAluSP:
  if (_trace) printf("DoBlock2ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock2ReadAluLP:
  if (_trace) printf("DoBlock2ReadAluLP:\n");

DoBlock2ReadAluFP:
  if (_trace) printf("DoBlock2ReadAluFP:\n");

begindoblock2readalu:
  if (_trace) printf("begindoblock2readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar2;   
  goto blockreadalu;   

DoBlock2ReadAluIM:
  goto doistageerror;

/* end DoBlock2ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock2ReadAlu */
/* start DoBlock1ReadAlu */

  /* Halfword operand from stack instruction - DoBlock1ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock1readalu:
  if (_trace) printf("doblock1readalu:\n");

DoBlock1ReadAluSP:
  if (_trace) printf("DoBlock1ReadAluSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoBlock1ReadAluLP:
  if (_trace) printf("DoBlock1ReadAluLP:\n");

DoBlock1ReadAluFP:
  if (_trace) printf("DoBlock1ReadAluFP:\n");

begindoblock1readalu:
  if (_trace) printf("begindoblock1readalu:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg2 = (u64)&processor->bar1;   

blockreadalu:
  if (_trace) printf("blockreadalu:\n");
  arg5 = *(u64 *)&(processor->stackcachebasevma);   
  arg6 = *(s32 *)&processor->scovlimit;   		// Size of the stack cache (words) 
  t1 = *(s32 *)arg2;   		// Get the vma 
  t5 = *(s32 *)arg1;   
  t4 = *(s32 *)(arg1 + 4);   
  t5 = (u32)t5;   
  t9 = t4 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i%block-n-read-alu16322;
  t1 = (u32)t1;   
  /* Memory Read Internal */

vma-memory-read16324:
  t11 = t1 + ivory;
  t3 = (t11 * 4);   
  t2 = LDQ_U(t11);   
  t9 = t1 - arg5;   		// Stack cache offset 
  t12 = *(u64 *)&(processor->dataread_mask);   
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;   		// In range? 
  t3 = *(s32 *)t3;   
  t2 = (u8)(t2 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma-memory-read16326;

vma-memory-read16325:
  t11 = zero + 240;   
  t12 = t12 >> (t2 & 63);   
  t11 = t11 >> (t2 & 63);   
  t3 = (u32)t3;   
  if (t12 & 1)   
    goto vma-memory-read16328;

vma-memory-read16335:
  t9 = t2 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i%block-n-read-alu16323;
  t1 = t1 + 1;		// Increment the address 
		/* Store updated vma in BAR */
  *(u32 *)arg2 = t1;
  t6 = *(u64 *)&(processor->aluop);   
  *(u64 *)&processor->aluoverflow = zero;   
  t7 = *(u64 *)&(processor->aluandrotatecontrol);   
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;   

force-alignment16396:
  if (_trace) printf("force-alignment16396:\n");
  if (t1 == 0) 
    goto basic-dispatch16337;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;   
  t8 = t8 & 15;		// Extract the ALU boolean function 
  t1 = (t8 == Boole_Clear) ? 1 : 0;   

force-alignment16356:
  if (_trace) printf("force-alignment16356:\n");
  if (t1 != 0)   
    goto basic-dispatch16338;

basic-dispatch16339:
  if (_trace) printf("basic-dispatch16339:\n");
  t1 = (t8 == Boole_And) ? 1 : 0;   

force-alignment16357:
  if (_trace) printf("force-alignment16357:\n");
  if (t1 == 0) 
    goto basic-dispatch16340;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto basic-dispatch16338;   

basic-dispatch16340:
  if (_trace) printf("basic-dispatch16340:\n");
  t1 = (t8 == Boole_AndC1) ? 1 : 0;   

force-alignment16358:
  if (_trace) printf("force-alignment16358:\n");
  if (t1 == 0) 
    goto basic-dispatch16341;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto basic-dispatch16338;   

basic-dispatch16341:
  if (_trace) printf("basic-dispatch16341:\n");
  t1 = (t8 == Boole_2) ? 1 : 0;   

force-alignment16359:
  if (_trace) printf("force-alignment16359:\n");
  if (t1 == 0) 
    goto basic-dispatch16342;
  /* Here if argument Boole2 */
  t8 = t5;
  goto basic-dispatch16338;   

basic-dispatch16342:
  if (_trace) printf("basic-dispatch16342:\n");
  t1 = (t8 == Boole_AndC2) ? 1 : 0;   

force-alignment16360:
  if (_trace) printf("force-alignment16360:\n");
  if (t1 == 0) 
    goto basic-dispatch16343;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto basic-dispatch16338;   

basic-dispatch16343:
  if (_trace) printf("basic-dispatch16343:\n");
  t1 = (t8 == Boole_1) ? 1 : 0;   

force-alignment16361:
  if (_trace) printf("force-alignment16361:\n");
  if (t1 == 0) 
    goto basic-dispatch16344;
  /* Here if argument Boole1 */
  t8 = t3;
  goto basic-dispatch16338;   

basic-dispatch16344:
  if (_trace) printf("basic-dispatch16344:\n");
  t1 = (t8 == Boole_Xor) ? 1 : 0;   

force-alignment16362:
  if (_trace) printf("force-alignment16362:\n");
  if (t1 == 0) 
    goto basic-dispatch16345;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;   
  goto basic-dispatch16338;   

basic-dispatch16345:
  if (_trace) printf("basic-dispatch16345:\n");
  t1 = (t8 == Boole_Ior) ? 1 : 0;   

force-alignment16363:
  if (_trace) printf("force-alignment16363:\n");
  if (t1 == 0) 
    goto basic-dispatch16346;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto basic-dispatch16338;   

basic-dispatch16346:
  if (_trace) printf("basic-dispatch16346:\n");
  t1 = (t8 == Boole_Nor) ? 1 : 0;   

force-alignment16364:
  if (_trace) printf("force-alignment16364:\n");
  if (t1 == 0) 
    goto basic-dispatch16347;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;   
  goto basic-dispatch16338;   

basic-dispatch16347:
  if (_trace) printf("basic-dispatch16347:\n");
  t1 = (t8 == Boole_Equiv) ? 1 : 0;   

force-alignment16365:
  if (_trace) printf("force-alignment16365:\n");
  if (t1 == 0) 
    goto basic-dispatch16348;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;   
  t8 = ~t8;   
  goto basic-dispatch16338;   

basic-dispatch16348:
  if (_trace) printf("basic-dispatch16348:\n");
  t1 = (t8 == Boole_C1) ? 1 : 0;   

force-alignment16366:
  if (_trace) printf("force-alignment16366:\n");
  if (t1 == 0) 
    goto basic-dispatch16349;
  /* Here if argument BooleC1 */
  t8 = ~t3;   
  goto basic-dispatch16338;   

basic-dispatch16349:
  if (_trace) printf("basic-dispatch16349:\n");
  t1 = (t8 == Boole_OrC1) ? 1 : 0;   

force-alignment16367:
  if (_trace) printf("force-alignment16367:\n");
  if (t1 == 0) 
    goto basic-dispatch16350;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);   
  goto basic-dispatch16338;   

basic-dispatch16350:
  if (_trace) printf("basic-dispatch16350:\n");
  t1 = (t8 == Boole_C2) ? 1 : 0;   

force-alignment16368:
  if (_trace) printf("force-alignment16368:\n");
  if (t1 == 0) 
    goto basic-dispatch16351;
  /* Here if argument BooleC2 */
  t8 = ~t5;   
  goto basic-dispatch16338;   

basic-dispatch16351:
  if (_trace) printf("basic-dispatch16351:\n");
  t1 = (t8 == Boole_OrC2) ? 1 : 0;   

force-alignment16369:
  if (_trace) printf("force-alignment16369:\n");
  if (t1 == 0) 
    goto basic-dispatch16352;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto basic-dispatch16338;   

basic-dispatch16352:
  if (_trace) printf("basic-dispatch16352:\n");
  t1 = (t8 == Boole_Nand) ? 1 : 0;   

force-alignment16370:
  if (_trace) printf("force-alignment16370:\n");
  if (t1 == 0) 
    goto basic-dispatch16353;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto basic-dispatch16338;   

basic-dispatch16353:
  if (_trace) printf("basic-dispatch16353:\n");
  t1 = (t8 == Boole_Set) ? 1 : 0;   

force-alignment16371:
  if (_trace) printf("force-alignment16371:\n");
  if (t1 == 0) 
    goto basic-dispatch16338;
  /* Here if argument BooleSet */
  t8 = ~zero;   

basic-dispatch16338:
  if (_trace) printf("basic-dispatch16338:\n");
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;   

basic-dispatch16337:
  if (_trace) printf("basic-dispatch16337:\n");
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;   

force-alignment16397:
  if (_trace) printf("force-alignment16397:\n");
  if (t1 == 0) 
    goto basic-dispatch16372;
  /* Here if argument ALUFunctionByte */
  t9 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t10 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t1 = t7 >> 10;   
  t1 = t1 & 3;		// Extract the byte background 
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;   

force-alignment16379:
  if (_trace) printf("force-alignment16379:\n");
  if (t11 == 0) 
    goto basic-dispatch16375;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

basic-dispatch16374:
  if (_trace) printf("basic-dispatch16374:\n");
  t12 = t7 >> 12;   
  t12 = t12 & 1;		// Extractthe byte rotate latch 
  t8 = t5 << (t9 & 63);   
  t11 = (u32)(t8 >> ((4&7)*8));   
  t8 = (u32)t8;   
  t8 = t8 | t11;		// OP2 rotated 
  if (t12 == 0) 		// Don't update rotate latch if not requested 
    goto alu-function-byte16373;
  *(u64 *)&processor->rotatelatch = t8;   

alu-function-byte16373:
  if (_trace) printf("alu-function-byte16373:\n");
  t12 = zero + -2;   
  t12 = t12 << (t10 & 63);   
  t12 = ~t12;   		// Compute mask 
  /* Get byte function */
  t11 = t7 >> 13;   
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;   

force-alignment16384:
  if (_trace) printf("force-alignment16384:\n");
  if (t10 == 0) 
    goto basic-dispatch16381;
  /* Here if argument ALUByteFunctionDpb */
  t12 = t12 << (t9 & 63);   		// Position mask 

basic-dispatch16380:
  if (_trace) printf("basic-dispatch16380:\n");
  t8 = t8 & t12;		// rotated&mask 
  t1 = t1 & ~t12;		// background&~mask 
  t8 = t8 | t1;
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;   

basic-dispatch16372:
  if (_trace) printf("basic-dispatch16372:\n");
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;   

force-alignment16398:
  if (_trace) printf("force-alignment16398:\n");
  if (t1 == 0) 
    goto basic-dispatch16385;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;   
  t10 = t10 & 3;		// Extract the op2 
  t9 = t7 >> 10;   
  t9 = t9 & 1;		// Extract the adder carry in 
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;   

force-alignment16393:
  if (_trace) printf("force-alignment16393:\n");
  if (t11 == 0) 
    goto basic-dispatch16388;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

basic-dispatch16387:
  if (_trace) printf("basic-dispatch16387:\n");
  t8 = t3 + t1;
  t8 = t8 + t9;
  t10 = t8 >> 31;   		// Sign bit 
  t11 = t8 >> 32;   		// Next bit 
  t10 = t10 ^ t11;   		// Low bit is now overflow indicator 
  t11 = t7 >> 24;   		// Get the load-carry-in bit 
  *(u64 *)&processor->aluoverflow = t10;   
  if ((t11 & 1) == 0)   
    goto alu-function-adder16386;
  t10 = (u32)(t8 >> ((4&7)*8));   		// Get the carry 
  t11 = zero + 1024;   
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;   
  t7 = t7 | t11;		// Set the adder carry in 
  *(u64 *)&processor->aluandrotatecontrol = t7;   

alu-function-adder16386:
  if (_trace) printf("alu-function-adder16386:\n");
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->aluborrow = t10;   
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->alulessthan = t10;   
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;   

basic-dispatch16385:
  if (_trace) printf("basic-dispatch16385:\n");
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;   

force-alignment16399:
  if (_trace) printf("force-alignment16399:\n");
  if (t1 == 0) 
    goto basic-dispatch16336;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;   

basic-dispatch16336:
  if (_trace) printf("basic-dispatch16336:\n");

i%block-n-read-alu16322:
  if (_trace) printf("i%block-n-read-alu16322:\n");
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);   
  t9 = arg1 - t9;   		// stack cache base relative offset 
  t9 = t9 >> 3;   		// convert byte address to word address 
  t1 = t9 + arg5;		// reconstruct VMA 
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

i%block-n-read-alu16323:
  if (_trace) printf("i%block-n-read-alu16323:\n");
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

basic-dispatch16388:
  if (_trace) printf("basic-dispatch16388:\n");
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;   

force-alignment16400:
  if (_trace) printf("force-alignment16400:\n");
  if (t11 == 0) 
    goto basic-dispatch16389;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto basic-dispatch16387;   

basic-dispatch16389:
  if (_trace) printf("basic-dispatch16389:\n");
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;   

force-alignment16401:
  if (_trace) printf("force-alignment16401:\n");
  if (t11 == 0) 
    goto basic-dispatch16390;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;   
  t1 = (u32)t1;   
  goto basic-dispatch16387;   

basic-dispatch16390:
  if (_trace) printf("basic-dispatch16390:\n");
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;   

force-alignment16402:
  if (_trace) printf("force-alignment16402:\n");
  if (t11 == 0) 
    goto basic-dispatch16387;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;   
  t1 = (u32)t1;   
  goto basic-dispatch16387;   

basic-dispatch16381:
  if (_trace) printf("basic-dispatch16381:\n");
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;   

force-alignment16403:
  if (_trace) printf("force-alignment16403:\n");
  if (t10 != 0)   
    goto basic-dispatch16380;
  goto basic-dispatch16380;   

basic-dispatch16375:
  if (_trace) printf("basic-dispatch16375:\n");
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force-alignment16404:
  if (_trace) printf("force-alignment16404:\n");
  if (t11 == 0) 
    goto basic-dispatch16376;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);   
  goto basic-dispatch16374;   

basic-dispatch16376:
  if (_trace) printf("basic-dispatch16376:\n");
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;   

force-alignment16405:
  if (_trace) printf("force-alignment16405:\n");
  if (t11 == 0) 
    goto basic-dispatch16374;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto basic-dispatch16374;   

vma-memory-read16326:
  if (_trace) printf("vma-memory-read16326:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t3 = *(s32 *)t9;   
  t2 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma-memory-read16325;   

vma-memory-read16328:
  if (_trace) printf("vma-memory-read16328:\n");
  if ((t11 & 1) == 0)   
    goto vma-memory-read16327;
  t1 = (u32)t3;   		// Do the indirect thing 
  goto vma-memory-read16324;   

vma-memory-read16327:
  if (_trace) printf("vma-memory-read16327:\n");
  t12 = *(u64 *)&(processor->dataread);   		// Load the memory action table for cycle 
  /* TagType. */
  t11 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = t1;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma-memory-read16332:
  if (_trace) printf("vma-memory-read16332:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma-memory-read16331;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma-memory-read16335;   

vma-memory-read16331:

vma-memory-read16330:
  /* Perform memory action */
  arg1 = t12;
  arg2 = 0;
  goto performmemoryaction;

DoBlock1ReadAluIM:
  goto doistageerror;

/* end DoBlock1ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock1ReadAlu */
/* start DoBlock0ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadTest */

doblock0readtest:
  if (_trace) printf("doblock0readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock0ReadTestIM:
  if (_trace) printf("DoBlock0ReadTestIM:\n");

DoBlock0ReadTestSP:
  if (_trace) printf("DoBlock0ReadTestSP:\n");

DoBlock0ReadTestLP:
  if (_trace) printf("DoBlock0ReadTestLP:\n");

DoBlock0ReadTestFP:
  if (_trace) printf("DoBlock0ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;   
  goto blockreadtest;   

/* end DoBlock0ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock0ReadTest */
/* start DoBlock3ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadTest */

doblock3readtest:
  if (_trace) printf("doblock3readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock3ReadTestIM:
  if (_trace) printf("DoBlock3ReadTestIM:\n");

DoBlock3ReadTestSP:
  if (_trace) printf("DoBlock3ReadTestSP:\n");

DoBlock3ReadTestLP:
  if (_trace) printf("DoBlock3ReadTestLP:\n");

DoBlock3ReadTestFP:
  if (_trace) printf("DoBlock3ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;   
  goto blockreadtest;   

/* end DoBlock3ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock3ReadTest */
/* start DoBlock2ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadTest */

doblock2readtest:
  if (_trace) printf("doblock2readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock2ReadTestIM:
  if (_trace) printf("DoBlock2ReadTestIM:\n");

DoBlock2ReadTestSP:
  if (_trace) printf("DoBlock2ReadTestSP:\n");

DoBlock2ReadTestLP:
  if (_trace) printf("DoBlock2ReadTestLP:\n");

DoBlock2ReadTestFP:
  if (_trace) printf("DoBlock2ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;   
  goto blockreadtest;   

/* end DoBlock2ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock2ReadTest */
/* start DoBlock1ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadTest */

doblock1readtest:
  if (_trace) printf("doblock1readtest:\n");
  /* Actually only one entry point, but simulate others for dispatch */

DoBlock1ReadTestIM:
  if (_trace) printf("DoBlock1ReadTestIM:\n");

DoBlock1ReadTestSP:
  if (_trace) printf("DoBlock1ReadTestSP:\n");

DoBlock1ReadTestLP:
  if (_trace) printf("DoBlock1ReadTestLP:\n");

DoBlock1ReadTestFP:
  if (_trace) printf("DoBlock1ReadTestFP:\n");
  arg1 = (u16)(arg3 >> ((4&7)*8));   
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;   

blockreadtest:
  if (_trace) printf("blockreadtest:\n");
  arg3 = *(s32 *)arg2;   		// Get the vma 
  t1 = arg1 >> 6;   		// cycle type 
  t5 = *(s32 *)iSP;   
  t4 = *(s32 *)(iSP + 4);   
  t5 = (u32)t5;   
  arg3 = (u32)arg3;   
  /* Memory Read Internal */

vma-memory-read16412:
  t9 = *(u64 *)&(processor->stackcachebasevma);   		// Base of stack cache 
  t11 = arg3 + ivory;
  t10 = *(s32 *)&processor->scovlimit;   
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t2 = LDQ_U(t11);   
  t12 = (t12 * 4) + ivory;   
  t3 = (t11 * 4);   
  t9 = arg3 - t9;   		// Stack cache offset 
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);   
  t10 = ((u64)t9 < (u64)t10) ? 1 : 0;   		// In range? 
  t3 = *(s32 *)t3;   
  t2 = (u8)(t2 >> ((t11&7)*8));   
  if (t10 != 0)   
    goto vma-memory-read16414;

vma-memory-read16413:
  t12 = t12 >> (t2 & 63);   
  t3 = (u32)t3;   
  if (t12 & 1)   
    goto vma-memory-read16416;

vma-memory-read16423:
  t1 = arg1 & 32;		// =fixnum onlyp 
  if (t1 == 0) 		// J. if we don't have to test for fixnump. 
    goto i%block-n-read-test16406;
  t9 = t2 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i%block-n-read-test16409;
  t9 = t4 - Type_Fixnum;   
  t9 = t9 & 63;		// Strip CDR code 
  if (t9 != 0)   
    goto i%block-n-read-test16410;

i%block-n-read-test16406:
  if (_trace) printf("i%block-n-read-test16406:\n");
  t1 = arg1 & 16;		// =cdr-code-nextp 
  if (t1 == 0) 		// J. if we don't have to clear CDR codes. 
    goto i%block-n-read-test16408;
  /* TagType. */
  t2 = t2 & 63;

i%block-n-read-test16408:
  if (_trace) printf("i%block-n-read-test16408:\n");
  t6 = *(u64 *)&(processor->aluop);   
  *(u64 *)&processor->aluoverflow = zero;   
  t7 = *(u64 *)&(processor->aluandrotatecontrol);   
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;   

force-alignment16484:
  if (_trace) printf("force-alignment16484:\n");
  if (t1 == 0) 
    goto basic-dispatch16425;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;   
  t8 = t8 & 15;		// Extract the ALU boolean function 
  t1 = (t8 == Boole_Clear) ? 1 : 0;   

force-alignment16444:
  if (_trace) printf("force-alignment16444:\n");
  if (t1 != 0)   
    goto basic-dispatch16426;

basic-dispatch16427:
  if (_trace) printf("basic-dispatch16427:\n");
  t1 = (t8 == Boole_And) ? 1 : 0;   

force-alignment16445:
  if (_trace) printf("force-alignment16445:\n");
  if (t1 == 0) 
    goto basic-dispatch16428;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto basic-dispatch16426;   

basic-dispatch16428:
  if (_trace) printf("basic-dispatch16428:\n");
  t1 = (t8 == Boole_AndC1) ? 1 : 0;   

force-alignment16446:
  if (_trace) printf("force-alignment16446:\n");
  if (t1 == 0) 
    goto basic-dispatch16429;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto basic-dispatch16426;   

basic-dispatch16429:
  if (_trace) printf("basic-dispatch16429:\n");
  t1 = (t8 == Boole_2) ? 1 : 0;   

force-alignment16447:
  if (_trace) printf("force-alignment16447:\n");
  if (t1 == 0) 
    goto basic-dispatch16430;
  /* Here if argument Boole2 */
  t8 = t5;
  goto basic-dispatch16426;   

basic-dispatch16430:
  if (_trace) printf("basic-dispatch16430:\n");
  t1 = (t8 == Boole_AndC2) ? 1 : 0;   

force-alignment16448:
  if (_trace) printf("force-alignment16448:\n");
  if (t1 == 0) 
    goto basic-dispatch16431;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto basic-dispatch16426;   

basic-dispatch16431:
  if (_trace) printf("basic-dispatch16431:\n");
  t1 = (t8 == Boole_1) ? 1 : 0;   

force-alignment16449:
  if (_trace) printf("force-alignment16449:\n");
  if (t1 == 0) 
    goto basic-dispatch16432;
  /* Here if argument Boole1 */
  t8 = t3;
  goto basic-dispatch16426;   

basic-dispatch16432:
  if (_trace) printf("basic-dispatch16432:\n");
  t1 = (t8 == Boole_Xor) ? 1 : 0;   

force-alignment16450:
  if (_trace) printf("force-alignment16450:\n");
  if (t1 == 0) 
    goto basic-dispatch16433;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;   
  goto basic-dispatch16426;   

basic-dispatch16433:
  if (_trace) printf("basic-dispatch16433:\n");
  t1 = (t8 == Boole_Ior) ? 1 : 0;   

force-alignment16451:
  if (_trace) printf("force-alignment16451:\n");
  if (t1 == 0) 
    goto basic-dispatch16434;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto basic-dispatch16426;   

basic-dispatch16434:
  if (_trace) printf("basic-dispatch16434:\n");
  t1 = (t8 == Boole_Nor) ? 1 : 0;   

force-alignment16452:
  if (_trace) printf("force-alignment16452:\n");
  if (t1 == 0) 
    goto basic-dispatch16435;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;   
  goto basic-dispatch16426;   

basic-dispatch16435:
  if (_trace) printf("basic-dispatch16435:\n");
  t1 = (t8 == Boole_Equiv) ? 1 : 0;   

force-alignment16453:
  if (_trace) printf("force-alignment16453:\n");
  if (t1 == 0) 
    goto basic-dispatch16436;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;   
  t8 = ~t8;   
  goto basic-dispatch16426;   

basic-dispatch16436:
  if (_trace) printf("basic-dispatch16436:\n");
  t1 = (t8 == Boole_C1) ? 1 : 0;   

force-alignment16454:
  if (_trace) printf("force-alignment16454:\n");
  if (t1 == 0) 
    goto basic-dispatch16437;
  /* Here if argument BooleC1 */
  t8 = ~t3;   
  goto basic-dispatch16426;   

basic-dispatch16437:
  if (_trace) printf("basic-dispatch16437:\n");
  t1 = (t8 == Boole_OrC1) ? 1 : 0;   

force-alignment16455:
  if (_trace) printf("force-alignment16455:\n");
  if (t1 == 0) 
    goto basic-dispatch16438;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);   
  goto basic-dispatch16426;   

basic-dispatch16438:
  if (_trace) printf("basic-dispatch16438:\n");
  t1 = (t8 == Boole_C2) ? 1 : 0;   

force-alignment16456:
  if (_trace) printf("force-alignment16456:\n");
  if (t1 == 0) 
    goto basic-dispatch16439;
  /* Here if argument BooleC2 */
  t8 = ~t5;   
  goto basic-dispatch16426;   

basic-dispatch16439:
  if (_trace) printf("basic-dispatch16439:\n");
  t1 = (t8 == Boole_OrC2) ? 1 : 0;   

force-alignment16457:
  if (_trace) printf("force-alignment16457:\n");
  if (t1 == 0) 
    goto basic-dispatch16440;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto basic-dispatch16426;   

basic-dispatch16440:
  if (_trace) printf("basic-dispatch16440:\n");
  t1 = (t8 == Boole_Nand) ? 1 : 0;   

force-alignment16458:
  if (_trace) printf("force-alignment16458:\n");
  if (t1 == 0) 
    goto basic-dispatch16441;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto basic-dispatch16426;   

basic-dispatch16441:
  if (_trace) printf("basic-dispatch16441:\n");
  t1 = (t8 == Boole_Set) ? 1 : 0;   

force-alignment16459:
  if (_trace) printf("force-alignment16459:\n");
  if (t1 == 0) 
    goto basic-dispatch16426;
  /* Here if argument BooleSet */
  t8 = ~zero;   

basic-dispatch16426:
  if (_trace) printf("basic-dispatch16426:\n");

basic-dispatch16424:
  if (_trace) printf("basic-dispatch16424:\n");
  t1 = t7 >> 16;   
  t1 = t1 & 31;		// Extract ALU condition 
  t10 = *(u64 *)&(processor->aluoverflow);   
  t11 = *(u64 *)&(processor->aluborrow);   
  t12 = *(u64 *)&(processor->alulessthan);   
  t9 = (t1 == ALUCondition_SignedLessThanOrEqual) ? 1 : 0;   

force-alignment16516:
  if (_trace) printf("force-alignment16516:\n");
  if (t9 == 0) 
    goto basic-dispatch16489;
  /* Here if argument ALUConditionSignedLessThanOrEqual */
  if (t12 != 0)   
    goto alu-compute-condition16485;
  if (t8 == 0) 
    goto alu-compute-condition16485;

basic-dispatch16488:
  if (_trace) printf("basic-dispatch16488:\n");

alu-compute-condition16486:
  if (_trace) printf("alu-compute-condition16486:\n");
  t1 = zero;
  goto alu-compute-condition16487;   

alu-compute-condition16485:
  if (_trace) printf("alu-compute-condition16485:\n");
  t1 = 1;

alu-compute-condition16487:
  if (_trace) printf("alu-compute-condition16487:\n");
  t9 = t7 >> 21;   
  t9 = t9 & 1;		// Extract the condition sense 
  t1 = t1 ^ t9;   
  if (t1 != 0)   
    goto i%block-n-read-test16411;
  t1 = arg1 & 4;		// =no-incrementp 
  if (t1 != 0)   		// J. if we don't have to increment the address. 
    goto i%block-n-read-test16407;
  arg3 = arg3 + 1;		// Increment the address 

i%block-n-read-test16407:
  if (_trace) printf("i%block-n-read-test16407:\n");
		/* Store updated vma in BAR */
  *(u32 *)arg2 = arg3;
  goto NEXTINSTRUCTION;   

i%block-n-read-test16411:
  if (_trace) printf("i%block-n-read-test16411:\n");
  t10 = *(s32 *)(iSP + -8);   
  t9 = *(s32 *)(iSP + -4);   
  t10 = (u32)t10;   
  t10 = t10 << 1;   
  iPC = t9 & 1;
  iPC = iPC + t10;
  goto interpretinstructionforjump;   

i%block-n-read-test16410:
  if (_trace) printf("i%block-n-read-test16410:\n");
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);   
  arg3 = *(u64 *)&(processor->stackcachebasevma);   
  t9 = iSP - t9;   		// stack cache base relative offset 
  t9 = t9 >> 3;   		// convert byte address to word address 
  arg3 = t9 + arg3;		// reconstruct VMA 
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

i%block-n-read-test16409:
  if (_trace) printf("i%block-n-read-test16409:\n");
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

basic-dispatch16489:
  if (_trace) printf("basic-dispatch16489:\n");
  t9 = (t1 == ALUCondition_SignedLessThan) ? 1 : 0;   

force-alignment16517:
  if (_trace) printf("force-alignment16517:\n");
  if (t9 == 0) 
    goto basic-dispatch16490;
  /* Here if argument ALUConditionSignedLessThan */
  if (t12 != 0)   
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16490:
  if (_trace) printf("basic-dispatch16490:\n");
  t9 = (t1 == ALUCondition_Negative) ? 1 : 0;   

force-alignment16518:
  if (_trace) printf("force-alignment16518:\n");
  if (t9 == 0) 
    goto basic-dispatch16491;
  /* Here if argument ALUConditionNegative */
  if ((s64)t8 < 0)   
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16491:
  if (_trace) printf("basic-dispatch16491:\n");
  t9 = (t1 == ALUCondition_SignedOverflow) ? 1 : 0;   

force-alignment16519:
  if (_trace) printf("force-alignment16519:\n");
  if (t9 == 0) 
    goto basic-dispatch16492;
  /* Here if argument ALUConditionSignedOverflow */
  if (t10 != 0)   
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16492:
  if (_trace) printf("basic-dispatch16492:\n");
  t9 = (t1 == ALUCondition_UnsignedLessThanOrEqual) ? 1 : 0;   

force-alignment16520:
  if (_trace) printf("force-alignment16520:\n");
  if (t9 == 0) 
    goto basic-dispatch16493;
  /* Here if argument ALUConditionUnsignedLessThanOrEqual */
  if (t11 != 0)   
    goto alu-compute-condition16485;
  if (t8 == 0) 
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16493:
  if (_trace) printf("basic-dispatch16493:\n");
  t9 = (t1 == ALUCondition_UnsignedLessThan) ? 1 : 0;   

force-alignment16521:
  if (_trace) printf("force-alignment16521:\n");
  if (t9 == 0) 
    goto basic-dispatch16494;
  /* Here if argument ALUConditionUnsignedLessThan */
  if (t11 != 0)   
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16494:
  if (_trace) printf("basic-dispatch16494:\n");
  t9 = (t1 == ALUCondition_Zero) ? 1 : 0;   

force-alignment16522:
  if (_trace) printf("force-alignment16522:\n");
  if (t9 == 0) 
    goto basic-dispatch16495;
  /* Here if argument ALUConditionZero */
  if (t8 == 0) 
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16495:
  if (_trace) printf("basic-dispatch16495:\n");
  t9 = (t1 == ALUCondition_High25Zero) ? 1 : 0;   

force-alignment16523:
  if (_trace) printf("force-alignment16523:\n");
  if (t9 == 0) 
    goto basic-dispatch16496;
  /* Here if argument ALUConditionHigh25Zero */
  t1 = t8 >> 7;   
  if (t1 == 0) 
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16496:
  if (_trace) printf("basic-dispatch16496:\n");
  t9 = (t1 == ALUCondition_Eq) ? 1 : 0;   

force-alignment16524:
  if (_trace) printf("force-alignment16524:\n");
  if (t9 == 0) 
    goto basic-dispatch16497;
  /* Here if argument ALUConditionEq */
  if (t8 != 0)   
    goto alu-compute-condition16486;
  t9 = t2 ^ t4;   
  /* TagType. */
  t9 = t9 & 63;
  if (t9 == 0) 
    goto alu-compute-condition16485;
  goto basic-dispatch16488;   

basic-dispatch16497:
  if (_trace) printf("basic-dispatch16497:\n");
  t9 = (t1 == ALUCondition_Op1Ephemeralp) ? 1 : 0;   

force-alignment16525:
  if (_trace) printf("force-alignment16525:\n");
  if (t9 == 0) 
    goto basic-dispatch16498;
  /* Here if argument ALUConditionOp1Ephemeralp */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16498:
  if (_trace) printf("basic-dispatch16498:\n");
  t9 = (t1 == ALUCondition_ResultTypeNil) ? 1 : 0;   

force-alignment16526:
  if (_trace) printf("force-alignment16526:\n");
  if (t9 == 0) 
    goto basic-dispatch16499;
  /* Here if argument ALUConditionResultTypeNil */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16499:
  if (_trace) printf("basic-dispatch16499:\n");
  t9 = (t1 == ALUCondition_Op2Fixnum) ? 1 : 0;   

force-alignment16527:
  if (_trace) printf("force-alignment16527:\n");
  if (t9 == 0) 
    goto basic-dispatch16500;
  /* Here if argument ALUConditionOp2Fixnum */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16500:
  if (_trace) printf("basic-dispatch16500:\n");
  t9 = (t1 == ALUCondition_False) ? 1 : 0;   

force-alignment16528:
  if (_trace) printf("force-alignment16528:\n");
  if (t9 == 0) 
    goto basic-dispatch16501;
  /* Here if argument ALUConditionFalse */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16501:
  if (_trace) printf("basic-dispatch16501:\n");
  t9 = (t1 == ALUCondition_ResultCdrLow) ? 1 : 0;   

force-alignment16529:
  if (_trace) printf("force-alignment16529:\n");
  if (t9 == 0) 
    goto basic-dispatch16502;
  /* Here if argument ALUConditionResultCdrLow */
  /* TagCdr. */
  t9 = t2 >> 6;   
  t1 = t9 & 1;
  goto alu-compute-condition16487;   

basic-dispatch16502:
  if (_trace) printf("basic-dispatch16502:\n");
  t9 = (t1 == ALUCondition_CleanupBitsSet) ? 1 : 0;   

force-alignment16530:
  if (_trace) printf("force-alignment16530:\n");
  if (t9 == 0) 
    goto basic-dispatch16503;
  /* Here if argument ALUConditionCleanupBitsSet */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16503:
  if (_trace) printf("basic-dispatch16503:\n");
  t9 = (t1 == ALUCondition_AddressInStackCache) ? 1 : 0;   

force-alignment16531:
  if (_trace) printf("force-alignment16531:\n");
  if (t9 == 0) 
    goto basic-dispatch16504;
  /* Here if argument ALUConditionAddressInStackCache */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16504:
  if (_trace) printf("basic-dispatch16504:\n");
  t9 = (t1 == ALUCondition_ExtraStackMode) ? 1 : 0;   

force-alignment16532:
  if (_trace) printf("force-alignment16532:\n");
  if (t9 == 0) 
    goto basic-dispatch16505;
  /* Here if argument ALUConditionExtraStackMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16505:
  if (_trace) printf("basic-dispatch16505:\n");
  t9 = (t1 == ALUCondition_FepMode) ? 1 : 0;   

force-alignment16533:
  if (_trace) printf("force-alignment16533:\n");
  if (t9 == 0) 
    goto basic-dispatch16506;
  /* Here if argument ALUConditionFepMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16506:
  if (_trace) printf("basic-dispatch16506:\n");
  t9 = (t1 == ALUCondition_FpCoprocessorPresent) ? 1 : 0;   

force-alignment16534:
  if (_trace) printf("force-alignment16534:\n");
  if (t9 == 0) 
    goto basic-dispatch16507;
  /* Here if argument ALUConditionFpCoprocessorPresent */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16507:
  if (_trace) printf("basic-dispatch16507:\n");
  t9 = (t1 == ALUCondition_Op1Oldspacep) ? 1 : 0;   

force-alignment16535:
  if (_trace) printf("force-alignment16535:\n");
  if (t9 == 0) 
    goto basic-dispatch16508;
  /* Here if argument ALUConditionOp1Oldspacep */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16508:
  if (_trace) printf("basic-dispatch16508:\n");
  t9 = (t1 == ALUCondition_PendingSequenceBreakEnabled) ? 1 : 0;   

force-alignment16536:
  if (_trace) printf("force-alignment16536:\n");
  if (t9 == 0) 
    goto basic-dispatch16509;
  /* Here if argument ALUConditionPendingSequenceBreakEnabled */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16509:
  if (_trace) printf("basic-dispatch16509:\n");
  t9 = (t1 == ALUCondition_Op1TypeAcceptable) ? 1 : 0;   

force-alignment16537:
  if (_trace) printf("force-alignment16537:\n");
  if (t9 == 0) 
    goto basic-dispatch16510;
  /* Here if argument ALUConditionOp1TypeAcceptable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16510:
  if (_trace) printf("basic-dispatch16510:\n");
  t9 = (t1 == ALUCondition_Op1TypeCondition) ? 1 : 0;   

force-alignment16538:
  if (_trace) printf("force-alignment16538:\n");
  if (t9 == 0) 
    goto basic-dispatch16511;
  /* Here if argument ALUConditionOp1TypeCondition */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16511:
  if (_trace) printf("basic-dispatch16511:\n");
  t9 = (t1 == ALUCondition_StackCacheOverflow) ? 1 : 0;   

force-alignment16539:
  if (_trace) printf("force-alignment16539:\n");
  if (t9 == 0) 
    goto basic-dispatch16512;
  /* Here if argument ALUConditionStackCacheOverflow */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16512:
  if (_trace) printf("basic-dispatch16512:\n");
  t9 = (t1 == ALUCondition_OrLogicVariable) ? 1 : 0;   

force-alignment16540:
  if (_trace) printf("force-alignment16540:\n");
  if (t9 == 0) 
    goto basic-dispatch16513;
  /* Here if argument ALUConditionOrLogicVariable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16513:
  if (_trace) printf("basic-dispatch16513:\n");
  /* Here for all other cases */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16425:
  if (_trace) printf("basic-dispatch16425:\n");
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;   

force-alignment16541:
  if (_trace) printf("force-alignment16541:\n");
  if (t1 == 0) 
    goto basic-dispatch16460;
  /* Here if argument ALUFunctionByte */
  t9 = *(u64 *)&(processor->byterotate);   		// Get rotate 
  t10 = *(u64 *)&(processor->bytesize);   		// Get bytesize 
  /* Get background */
  t1 = t7 >> 10;   
  t1 = t1 & 3;		// Extract the byte background 
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;   

force-alignment16467:
  if (_trace) printf("force-alignment16467:\n");
  if (t11 == 0) 
    goto basic-dispatch16463;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

basic-dispatch16462:
  if (_trace) printf("basic-dispatch16462:\n");
  t12 = t7 >> 12;   
  t12 = t12 & 1;		// Extractthe byte rotate latch 
  t8 = t5 << (t9 & 63);   
  t11 = (u32)(t8 >> ((4&7)*8));   
  t8 = (u32)t8;   
  t8 = t8 | t11;		// OP2 rotated 
  if (t12 == 0) 		// Don't update rotate latch if not requested 
    goto alu-function-byte16461;
  *(u64 *)&processor->rotatelatch = t8;   

alu-function-byte16461:
  if (_trace) printf("alu-function-byte16461:\n");
  t12 = zero + -2;   
  t12 = t12 << (t10 & 63);   
  t12 = ~t12;   		// Compute mask 
  /* Get byte function */
  t11 = t7 >> 13;   
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;   

force-alignment16472:
  if (_trace) printf("force-alignment16472:\n");
  if (t10 == 0) 
    goto basic-dispatch16469;
  /* Here if argument ALUByteFunctionDpb */
  t12 = t12 << (t9 & 63);   		// Position mask 

basic-dispatch16468:
  if (_trace) printf("basic-dispatch16468:\n");
  t8 = t8 & t12;		// rotated&mask 
  t1 = t1 & ~t12;		// background&~mask 
  t8 = t8 | t1;
  goto basic-dispatch16424;   

basic-dispatch16460:
  if (_trace) printf("basic-dispatch16460:\n");
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;   

force-alignment16542:
  if (_trace) printf("force-alignment16542:\n");
  if (t1 == 0) 
    goto basic-dispatch16473;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;   
  t10 = t10 & 3;		// Extract the op2 
  t9 = t7 >> 10;   
  t9 = t9 & 1;		// Extract the adder carry in 
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;   

force-alignment16481:
  if (_trace) printf("force-alignment16481:\n");
  if (t11 == 0) 
    goto basic-dispatch16476;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

basic-dispatch16475:
  if (_trace) printf("basic-dispatch16475:\n");
  t8 = t3 + t1;
  t8 = t8 + t9;
  t10 = t8 >> 31;   		// Sign bit 
  t11 = t8 >> 32;   		// Next bit 
  t10 = t10 ^ t11;   		// Low bit is now overflow indicator 
  t11 = t7 >> 24;   		// Get the load-carry-in bit 
  *(u64 *)&processor->aluoverflow = t10;   
  if ((t11 & 1) == 0)   
    goto alu-function-adder16474;
  t10 = (u32)(t8 >> ((4&7)*8));   		// Get the carry 
  t11 = zero + 1024;   
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;   
  t7 = t7 | t11;		// Set the adder carry in 
  *(u64 *)&processor->aluandrotatecontrol = t7;   

alu-function-adder16474:
  if (_trace) printf("alu-function-adder16474:\n");
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->aluborrow = t10;   
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;   
  *(u64 *)&processor->alulessthan = t10;   
  goto basic-dispatch16424;   

basic-dispatch16473:
  if (_trace) printf("basic-dispatch16473:\n");
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;   

force-alignment16543:
  if (_trace) printf("force-alignment16543:\n");
  if (t1 == 0) 
    goto basic-dispatch16424;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

basic-dispatch16476:
  if (_trace) printf("basic-dispatch16476:\n");
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;   

force-alignment16544:
  if (_trace) printf("force-alignment16544:\n");
  if (t11 == 0) 
    goto basic-dispatch16477;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto basic-dispatch16475;   

basic-dispatch16477:
  if (_trace) printf("basic-dispatch16477:\n");
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;   

force-alignment16545:
  if (_trace) printf("force-alignment16545:\n");
  if (t11 == 0) 
    goto basic-dispatch16478;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;   
  t1 = (u32)t1;   
  goto basic-dispatch16475;   

basic-dispatch16478:
  if (_trace) printf("basic-dispatch16478:\n");
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;   

force-alignment16546:
  if (_trace) printf("force-alignment16546:\n");
  if (t11 == 0) 
    goto basic-dispatch16475;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;   
  t1 = (u32)t1;   
  goto basic-dispatch16475;   

basic-dispatch16469:
  if (_trace) printf("basic-dispatch16469:\n");
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;   

force-alignment16547:
  if (_trace) printf("force-alignment16547:\n");
  if (t10 != 0)   
    goto basic-dispatch16468;
  goto basic-dispatch16468;   

basic-dispatch16463:
  if (_trace) printf("basic-dispatch16463:\n");
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;   

force-alignment16548:
  if (_trace) printf("force-alignment16548:\n");
  if (t11 == 0) 
    goto basic-dispatch16464;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);   
  goto basic-dispatch16462;   

basic-dispatch16464:
  if (_trace) printf("basic-dispatch16464:\n");
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;   

force-alignment16549:
  if (_trace) printf("force-alignment16549:\n");
  if (t11 == 0) 
    goto basic-dispatch16462;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto basic-dispatch16462;   

vma-memory-read16414:
  if (_trace) printf("vma-memory-read16414:\n");
  t10 = *(u64 *)&(processor->stackcachedata);   
  t9 = (t9 * 8) + t10;  		// reconstruct SCA 
  t3 = *(s32 *)t9;   
  t2 = *(s32 *)(t9 + 4);   		// Read from stack cache 
  goto vma-memory-read16413;   

vma-memory-read16416:
  if (_trace) printf("vma-memory-read16416:\n");

vma-memory-read16415:
  if (_trace) printf("vma-memory-read16415:\n");
  t12 = (t1 * 4);   		// Cycle-number -> table offset 
  t12 = (t12 * 4) + ivory;   
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);   
  /* TagType. */
  t11 = t2 & 63;		// Discard the CDR code 
  *(u64 *)&processor->vma = arg3;   		// stash the VMA for the (likely) trap 
  t11 = (t11 * 4) + t12;   		// Adjust for a longword load 
  t12 = *(s32 *)t11;   		// Get the memory action 

vma-memory-read16421:
  if (_trace) printf("vma-memory-read16421:\n");
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0) 
    goto vma-memory-read16420;
  arg3 = (u32)t3;   		// Do the indirect thing 
  goto vma-memory-read16412;   

vma-memory-read16420:
  if (_trace) printf("vma-memory-read16420:\n");
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0) 
    goto vma-memory-read16419;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto vma-memory-read16423;   

vma-memory-read16419:

vma-memory-read16418:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock1ReadTest */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunblok.as */
