/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * ANY CHANGES MADE TO THIS FILE WILL BE LOST
 *
 * File translated:      ../alpha-emulator/ifunpred.as
 ************************************************************************/

  /* Predicates. */
/* start DoEql */

  /* Halfword operand from stack instruction - DoEql */
  /* arg2 has the preloaded 8 bit operand. */

doeql:
  if (_trace) printf("doeql:\n");

DoEqlSP:
  if (_trace) printf("DoEqlSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 == 0)   		// SP-pop mode 
    arg1 = iSP;
  if (arg2 == 0)   		// Adjust SP if SP-pop mode 
    iSP = arg4;

DoEqlLP:
  if (_trace) printf("DoEqlLP:\n");

DoEqlFP:
  if (_trace) printf("DoEqlFP:\n");

headdoeql:
  if (_trace) printf("headdoeql:\n");
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  arg1 = *(u64 *)arg1;   		// Get the operand 

begindoeql:
  if (_trace) printf("begindoeql:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg6 = arg3 >> 12;   
  t3 = *(u64 *)iSP;   		// Load arg1 into t3 
  t4 = zero + -2048;   		// Low part of EQ-NOT-EQL mask 
  t11 = *(u64 *)&(processor->niladdress);   
  t4 = t4 + ((1) << 16);   		// High part of EQ-NOT-EQL mask 
  t12 = *(u64 *)&(processor->taddress);   		// Assume result will be T 
  t5 = arg1 ^ t3;   
  t5 = t5 << 26;   		// Shift left to lose CDRCODE. 
  arg6 = arg6 & 1;		// 1 if no-pop, 0 if pop 
  if (t5 == 0) 
    goto eqldone;
  /* They are not EQ, if types different or not numeric return nil */
  t5 = t5 >> 58;   		// Get the tag alone 
  t12 = t11;		// Now assume result will be NIL 
  if (t5 != 0)   		// Return NIL if tags different 
    goto eqldone;
  t3 = t3 >> 32;   		// Get tag, check for numeric 
  /* TagType. */
  t3 = t3 & 63;
  t4 = t4 >> (t3 & 63);   		// Type is now a bit mask 
  if (t4 & 1)   		// If funny numeric type, exception 
    goto eqlexc;

eqldone:
  if (_trace) printf("eqldone:\n");
  iSP = (arg6 * 8) + iSP;  		// Either a stack-push or a stack-write 
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  *(u64 *)iSP = t12;   
  goto cachevalid;   

DoEqlIM:
  if (_trace) printf("DoEqlIM:\n");
  arg2 = arg2 << 56;   
  t4 = *(s32 *)(iSP + 4);   		// t4=tag t3=data 
  t3 = *(s32 *)iSP;   
  arg6 = arg3 >> 12;   
  arg2 = (s64)arg2 >> 56;   		// Sign extension of arg2 is complete 
  t3 = (u32)t3;   
  t11 = *(u64 *)&(processor->niladdress);   
  /* TagType. */
  t4 = t4 & 63;
  t12 = *(u64 *)&(processor->taddress);   
  arg2 = (s32)t3 - (s32)arg2;   
  t4 = t4 ^ Type_Fixnum;   
  arg6 = arg6 & 1;		// 1 if no-pop, 0 if pop 
  t4 = arg2 | t4;
  iSP = (arg6 * 8) + iSP;  		// Either a stack-push or a stack-write 
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  if (t4 == 0)   
    t11 = t12;
  *(u64 *)iSP = t11;   		// Yes Virginia, this does dual issue with above 
  goto cachevalid;   

eqlexc:
  if (_trace) printf("eqlexc:\n");
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto exception;

/* end DoEql */
  /* End of Halfword operand from stack instruction - DoEql */
/* start DoGreaterp */

  /* Halfword operand from stack instruction - DoGreaterp */
  /* arg2 has the preloaded 8 bit operand. */

dogreaterp:
  if (_trace) printf("dogreaterp:\n");

DoGreaterpSP:
  if (_trace) printf("DoGreaterpSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 != 0)   
    goto begindogreaterp;
  arg6 = *(u64 *)arg4;   		// SP-pop, Reload TOS 
  arg1 = iSP;		// SP-pop mode 
  iSP = arg4;		// Adjust SP 

DoGreaterpLP:
  if (_trace) printf("DoGreaterpLP:\n");

DoGreaterpFP:
  if (_trace) printf("DoGreaterpFP:\n");

begindogreaterp:
  if (_trace) printf("begindogreaterp:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  t11 = *(u64 *)&(processor->niladdress);   
  t7 = arg3 >> 12;   
  t12 = *(u64 *)&(processor->taddress);   
  arg3 = (u32)(arg6 >> ((4&7)*8));   		// Get ARG1 tag 
  t1 = *(s32 *)(arg1 + 4);   		// t1 is tag of arg2 
  LDS(1, f1, *(u32 *)iSP );   
  t7 = t7 & 1;
  arg2 = *(s32 *)arg1;   
  arg4 = (s32)arg6;
  LDS(2, f2, *(u32 *)arg1 );   
  t5 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = t1 & 63;		// Strip off any CDR code bits. 
  t6 = (t5 == Type_Fixnum) ? 1 : 0;   

force_alignment32125:
  if (_trace) printf("force_alignment32125:\n");
  if (t6 == 0) 
    goto basic_dispatch32113;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;   

force_alignment32117:
  if (_trace) printf("force_alignment32117:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32108;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;   
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iSP = (t7 * 8) + iSP;  		// Pop/No-pop 
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  if ((s64)t2 > 0)   		// T if the test succeeds 
    t11 = t12;
  *(u64 *)iSP = t11;   
  goto cachevalid;   

basic_dispatch32114:
  if (_trace) printf("basic_dispatch32114:\n");

basic_dispatch32113:
  if (_trace) printf("basic_dispatch32113:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;   

force_alignment32126:
  if (_trace) printf("force_alignment32126:\n");
  if (t6 == 0) 
    goto basic_dispatch32118;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;   

force_alignment32122:
  if (_trace) printf("force_alignment32122:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32108;
  /* Here if argument TypeSingleFloat */

greaterpmmexcfltflt:
  if (_trace) printf("greaterpmmexcfltflt:\n");
  SETFLTT(3,f3, FLTU64(1,f1) <= FLTU64(2,f2) ? 2.0:0);  
  /* trapb force the trap to occur here */   		// Force the trap to occur here 
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iSP = (t7 * 8) + iSP;  
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  *(u64 *)iSP = t12;   
  if (FLTU64(3, f3) == 0.0)   
    goto cachevalid;
  *(u64 *)iSP = t11;   		// Didn't branch, answer is NIL 
  goto cachevalid;   

basic_dispatch32119:
  if (_trace) printf("basic_dispatch32119:\n");

basic_dispatch32118:
  if (_trace) printf("basic_dispatch32118:\n");
  /* Here for all other cases */

binary_type_dispatch32108:
  if (_trace) printf("binary_type_dispatch32108:\n");
  goto greaterpmmexc;   

basic_dispatch32112:
  if (_trace) printf("basic_dispatch32112:\n");

DoGreaterpIM:
  if (_trace) printf("DoGreaterpIM:\n");
  t11 = *(u64 *)&(processor->niladdress);   
  arg2 = arg2 << 56;   		// First half of sign extension 
  t12 = *(u64 *)&(processor->taddress);   
  t7 = arg3 >> 12;   
  arg3 = (u32)(arg6 >> ((4&7)*8));   
  arg4 = (s32)arg6;
  arg2 = (s64)arg2 >> 56;   		// Second half of sign extension 
  t7 = t7 & 1;
  t3 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = (t3 == Type_Fixnum) ? 1 : 0;   

force_alignment32131:
  if (_trace) printf("force_alignment32131:\n");
  if (t4 == 0) 
    goto basic_dispatch32128;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;   
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iSP = (t7 * 8) + iSP;  
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  if ((s64)t2 > 0)   		// T if the test succeeds 
    t11 = t12;
  *(u64 *)iSP = t11;   
  goto cachevalid;   

basic_dispatch32128:
  if (_trace) printf("basic_dispatch32128:\n");
  /* Here for all other cases */
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

basic_dispatch32127:
  if (_trace) printf("basic_dispatch32127:\n");

/* end DoGreaterp */
  /* End of Halfword operand from stack instruction - DoGreaterp */
/* start DoLogtest */

  /* Halfword operand from stack instruction - DoLogtest */
  /* arg2 has the preloaded 8 bit operand. */

dologtest:
  if (_trace) printf("dologtest:\n");

DoLogtestSP:
  if (_trace) printf("DoLogtestSP:\n");
  arg1 = arg5;		// Assume SP mode 
  if (arg2 != 0)   
    goto begindologtest;
  arg6 = *(u64 *)arg4;   		// SP-pop, Reload TOS 
  arg1 = iSP;		// SP-pop mode 
  iSP = arg4;		// Adjust SP 

DoLogtestLP:
  if (_trace) printf("DoLogtestLP:\n");

DoLogtestFP:
  if (_trace) printf("DoLogtestFP:\n");

begindologtest:
  if (_trace) printf("begindologtest:\n");
  /* arg1 has the operand address. */
  arg1 = (arg2 * 8) + arg1;  		// Compute operand address 
  t11 = *(u64 *)&(processor->niladdress);   
  t7 = arg3 >> 12;   
  t12 = *(u64 *)&(processor->taddress);   
  arg3 = (u32)(arg6 >> ((4&7)*8));   		// Get ARG1 tag 
  arg2 = *(s32 *)arg1;   
  LDS(1, f1, *(u32 *)iSP );   
  t7 = t7 & 1;
  t1 = *(s32 *)(arg1 + 4);   		// t1 is tag of arg2 
  arg4 = (u32)arg6;   
  arg2 = (u32)arg2;   
  LDS(2, f2, *(u32 *)arg1 );   
  t5 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = t1 & 63;		// Strip off any CDR code bits. 
  t6 = (t5 == Type_Fixnum) ? 1 : 0;   

force_alignment32144:
  if (_trace) printf("force_alignment32144:\n");
  if (t6 == 0) 
    goto basic_dispatch32137;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;   

force_alignment32141:
  if (_trace) printf("force_alignment32141:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32134;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iSP = (t7 * 8) + iSP;  		// Pop/No-pop 
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  if (t2)   		// T if the test succeeds 
    t11 = t12;
  *(u64 *)iSP = t11;   
  goto cachevalid;   

basic_dispatch32138:
  if (_trace) printf("basic_dispatch32138:\n");

basic_dispatch32137:
  if (_trace) printf("basic_dispatch32137:\n");
  /* Here for all other cases */

binary_type_dispatch32133:
  if (_trace) printf("binary_type_dispatch32133:\n");
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;
  goto binary_type_dispatch32135;   

binary_type_dispatch32134:
  if (_trace) printf("binary_type_dispatch32134:\n");
  arg6 = t1;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

binary_type_dispatch32135:
  if (_trace) printf("binary_type_dispatch32135:\n");

basic_dispatch32136:
  if (_trace) printf("basic_dispatch32136:\n");

DoLogtestIM:
  if (_trace) printf("DoLogtestIM:\n");
  t11 = *(u64 *)&(processor->niladdress);   
  arg2 = arg2 << 56;   		// First half of sign extension 
  t12 = *(u64 *)&(processor->taddress);   
  t7 = arg3 >> 12;   
  arg3 = (u32)(arg6 >> ((4&7)*8));   
  arg4 = (s32)arg6;
  arg2 = (s64)arg2 >> 56;   		// Second half of sign extension 
  t7 = t7 & 1;
  t3 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = (t3 == Type_Fixnum) ? 1 : 0;   

force_alignment32149:
  if (_trace) printf("force_alignment32149:\n");
  if (t4 == 0) 
    goto basic_dispatch32146;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);   
  iSP = (t7 * 8) + iSP;  
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);   
  if (t2)   		// T if the test succeeds 
    t11 = t12;
  *(u64 *)iSP = t11;   
  goto cachevalid;   

basic_dispatch32146:
  if (_trace) printf("basic_dispatch32146:\n");
  /* Here for all other cases */
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

basic_dispatch32145:
  if (_trace) printf("basic_dispatch32145:\n");

/* end DoLogtest */
  /* End of Halfword operand from stack instruction - DoLogtest */
/* start EqualNumberMMExc */


equalnumbermmexc:
  if (_trace) printf("equalnumbermmexc:\n");
  t5 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = t1 & 63;		// Strip off any CDR code bits. 
  t6 = (t5 == Type_Fixnum) ? 1 : 0;   

force_alignment32167:
  if (_trace) printf("force_alignment32167:\n");
  if (t6 == 0) 
    goto basic_dispatch32155;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;   

force_alignment32159:
  if (_trace) printf("force_alignment32159:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32152;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto equalnumbermmexcfltflt;   

basic_dispatch32156:
  if (_trace) printf("basic_dispatch32156:\n");

basic_dispatch32155:
  if (_trace) printf("basic_dispatch32155:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;   

force_alignment32168:
  if (_trace) printf("force_alignment32168:\n");
  if (t6 == 0) 
    goto basic_dispatch32160;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;   

force_alignment32164:
  if (_trace) printf("force_alignment32164:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32152;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto equalnumbermmexcfltflt;   

basic_dispatch32161:
  if (_trace) printf("basic_dispatch32161:\n");

basic_dispatch32160:
  if (_trace) printf("basic_dispatch32160:\n");
  /* Here for all other cases */

binary_type_dispatch32151:
  if (_trace) printf("binary_type_dispatch32151:\n");
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;
  goto binary_type_dispatch32153;   

binary_type_dispatch32152:
  if (_trace) printf("binary_type_dispatch32152:\n");
  arg6 = t1;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

binary_type_dispatch32153:
  if (_trace) printf("binary_type_dispatch32153:\n");

basic_dispatch32154:
  if (_trace) printf("basic_dispatch32154:\n");

/* end EqualNumberMMExc */
/* start LesspMMExc */


lesspmmexc:
  if (_trace) printf("lesspmmexc:\n");
  t5 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = t1 & 63;		// Strip off any CDR code bits. 
  t6 = (t5 == Type_Fixnum) ? 1 : 0;   

force_alignment32186:
  if (_trace) printf("force_alignment32186:\n");
  if (t6 == 0) 
    goto basic_dispatch32174;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;   

force_alignment32178:
  if (_trace) printf("force_alignment32178:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32171;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto lesspmmexcfltflt;   

basic_dispatch32175:
  if (_trace) printf("basic_dispatch32175:\n");

basic_dispatch32174:
  if (_trace) printf("basic_dispatch32174:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;   

force_alignment32187:
  if (_trace) printf("force_alignment32187:\n");
  if (t6 == 0) 
    goto basic_dispatch32179;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;   

force_alignment32183:
  if (_trace) printf("force_alignment32183:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32171;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto lesspmmexcfltflt;   

basic_dispatch32180:
  if (_trace) printf("basic_dispatch32180:\n");

basic_dispatch32179:
  if (_trace) printf("basic_dispatch32179:\n");
  /* Here for all other cases */

binary_type_dispatch32170:
  if (_trace) printf("binary_type_dispatch32170:\n");
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;
  goto binary_type_dispatch32172;   

binary_type_dispatch32171:
  if (_trace) printf("binary_type_dispatch32171:\n");
  arg6 = t1;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

binary_type_dispatch32172:
  if (_trace) printf("binary_type_dispatch32172:\n");

basic_dispatch32173:
  if (_trace) printf("basic_dispatch32173:\n");

/* end LesspMMExc */
/* start GreaterpMMExc */


greaterpmmexc:
  if (_trace) printf("greaterpmmexc:\n");
  t5 = arg3 & 63;		// Strip off any CDR code bits. 
  t4 = t1 & 63;		// Strip off any CDR code bits. 
  t6 = (t5 == Type_Fixnum) ? 1 : 0;   

force_alignment32205:
  if (_trace) printf("force_alignment32205:\n");
  if (t6 == 0) 
    goto basic_dispatch32193;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;   

force_alignment32197:
  if (_trace) printf("force_alignment32197:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32190;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto greaterpmmexcfltflt;   

basic_dispatch32194:
  if (_trace) printf("basic_dispatch32194:\n");

basic_dispatch32193:
  if (_trace) printf("basic_dispatch32193:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;   

force_alignment32206:
  if (_trace) printf("force_alignment32206:\n");
  if (t6 == 0) 
    goto basic_dispatch32198;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;   

force_alignment32202:
  if (_trace) printf("force_alignment32202:\n");
  if (t3 == 0) 
    goto binary_type_dispatch32190;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto greaterpmmexcfltflt;   

basic_dispatch32199:
  if (_trace) printf("basic_dispatch32199:\n");

basic_dispatch32198:
  if (_trace) printf("basic_dispatch32198:\n");
  /* Here for all other cases */

binary_type_dispatch32189:
  if (_trace) printf("binary_type_dispatch32189:\n");
  arg6 = arg3;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;
  goto binary_type_dispatch32191;   

binary_type_dispatch32190:
  if (_trace) printf("binary_type_dispatch32190:\n");
  arg6 = t1;		// arg6 = tag to dispatch on 
  arg3 = 0;		// arg3 = stackp 
  arg1 = 2;		// arg1 = instruction arity 
  arg4 = 1;		// arg4 = arithmeticp 
  goto numericexception;

binary_type_dispatch32191:
  if (_trace) printf("binary_type_dispatch32191:\n");

basic_dispatch32192:
  if (_trace) printf("basic_dispatch32192:\n");

/* end GreaterpMMExc */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunpred.as */
